package ni.com.sts.estudioCohorteCSSFV.modelo;

// Generated 01-oct-2015 22:10:46 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import ni.com.sts.estudioCohorteCSSFV.modelo.TipoConsulta;

/**
 * Admision generated by hbm2java
 */
@Entity
@Table(name = "admision", schema = "public")
public class Admision implements java.io.Serializable {

	private int secAdmision;
	private TipoConsulta tipoConsulta;
	private int codExpediente;
	private Date fechaSalida;
	private Short usuarioEntrega;
	private Short usuarioRecibe;
	private String observaSalida;
	private Date fechaEntrada;
	private Short usuarioRegresa;
	private String observaEntrada;
	private Integer numHojaConsulta;
	private Short ordenLlegada;

	public Admision() {
	}

	public Admision(int secAdmision, TipoConsulta tipoConsulta,
			int codExpediente, Date fechaSalida, short usuarioEntrega) {
		this.secAdmision = secAdmision;
		this.tipoConsulta = tipoConsulta;
		this.codExpediente = codExpediente;
		this.fechaSalida = fechaSalida;
		this.usuarioEntrega = usuarioEntrega;
	}

	public Admision(int secAdmision, TipoConsulta tipoConsulta,
			int codExpediente, Date fechaSalida, short usuarioEntrega,
			Short usuarioRecibe, String observaSalida, Date fechaEntrada,
			Short usuarioRegresa, String observaEntrada,
			Integer numHojaConsulta, Short ordenLlegada) {
		this.secAdmision = secAdmision;
		this.tipoConsulta = tipoConsulta;
		this.codExpediente = codExpediente;
		this.fechaSalida = fechaSalida;
		this.usuarioEntrega = usuarioEntrega;
		this.usuarioRecibe = usuarioRecibe;
		this.observaSalida = observaSalida;
		this.fechaEntrada = fechaEntrada;
		this.usuarioRegresa = usuarioRegresa;
		this.observaEntrada = observaEntrada;
		this.numHojaConsulta = numHojaConsulta;
		this.ordenLlegada = ordenLlegada;
	}

	@Id
	@SequenceGenerator(name = "id_admision_seq", sequenceName = "admision_sec_admision_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "id_admision_seq")
	@Column(name = "sec_admision", unique = true, nullable = false)	
	public int getSecAdmision() {
		return this.secAdmision;
	}

	public void setSecAdmision(int secAdmision) {
		this.secAdmision = secAdmision;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tipo_consulta", referencedColumnName="codigo", nullable = false)
	public TipoConsulta getTipoConsulta() {
		return this.tipoConsulta;
	}

	public void setTipoConsulta(TipoConsulta tipoConsulta) {
		this.tipoConsulta = tipoConsulta;
	}

	@Column(name = "cod_expediente", nullable = false)
	public int getCodExpediente() {
		return this.codExpediente;
	}

	public void setCodExpediente(int codExpediente) {
		this.codExpediente = codExpediente;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_salida", nullable = false, length = 29)
	public Date getFechaSalida() {
		return this.fechaSalida;
	}

	public void setFechaSalida(Date fechaSalida) {
		this.fechaSalida = fechaSalida;
	}

	@Column(name = "usuario_entrega", nullable = false)
	public Short getUsuarioEntrega() {
		return this.usuarioEntrega;
	}

	public void setUsuarioEntrega(Short usuarioEntrega) {
		this.usuarioEntrega = usuarioEntrega;
	}

	@Column(name = "usuario_recibe")
	public Short getUsuarioRecibe() {
		return this.usuarioRecibe;
	}

	public void setUsuarioRecibe(Short usuarioRecibe) {
		this.usuarioRecibe = usuarioRecibe;
	}

	@Column(name = "observa_salida", length = 100)
	public String getObservaSalida() {
		return this.observaSalida;
	}

	public void setObservaSalida(String observaSalida) {
		this.observaSalida = observaSalida;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_entrada", length = 29)
	public Date getFechaEntrada() {
		return this.fechaEntrada;
	}

	public void setFechaEntrada(Date fechaEntrada) {
		this.fechaEntrada = fechaEntrada;
	}

	@Column(name = "usuario_regresa")
	public Short getUsuarioRegresa() {
		return this.usuarioRegresa;
	}

	public void setUsuarioRegresa(Short usuarioRegresa) {
		this.usuarioRegresa = usuarioRegresa;
	}

	@Column(name = "observa_entrada", length = 100)
	public String getObservaEntrada() {
		return this.observaEntrada;
	}

	public void setObservaEntrada(String observaEntrada) {
		this.observaEntrada = observaEntrada;
	}

	@Column(name = "num_hoja_consulta")
	public Integer getNumHojaConsulta() {
		return this.numHojaConsulta;
	}

	public void setNumHojaConsulta(Integer numHojaConsulta) {
		this.numHojaConsulta = numHojaConsulta;
	}

	@Column(name = "orden_llegada")
	public Short getOrdenLlegada() {
		return this.ordenLlegada;
	}

	public void setOrdenLlegada(Short ordenLlegada) {
		this.ordenLlegada = ordenLlegada;
	}

}
