package ni.com.sts.estudioCohorteCSSFV.modelo;
// Generated 04-30-2019 09:50:59 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Departamentos generated by hbm2java
 */
@Entity
@Table(name = "departamentos")
public class Departamentos implements java.io.Serializable {

	private int divisionpoliticaId;
	private String nombre;
	private int codigoNacional;
	private String codigoIso;

	public Departamentos() {
	}

	public Departamentos(int divisionpoliticaId, String nombre, int codigoNacional, String codigoIso) {
		this.divisionpoliticaId = divisionpoliticaId;
		this.nombre = nombre;
		this.codigoNacional = codigoNacional;
		this.codigoIso = codigoIso;
	}

	@Id

	@Column(name = "divisionpolitica_id", unique = true, nullable = false)
	public int getDivisionpoliticaId() {
		return this.divisionpoliticaId;
	}

	public void setDivisionpoliticaId(int divisionpoliticaId) {
		this.divisionpoliticaId = divisionpoliticaId;
	}

	@Column(name = "nombre", nullable = false, length = 64)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "codigo_nacional", nullable = false)
	public int getCodigoNacional() {
		return this.codigoNacional;
	}

	public void setCodigoNacional(int codigoNacional) {
		this.codigoNacional = codigoNacional;
	}

	@Column(name = "codigo_iso", nullable = false, length = 2)
	public String getCodigoIso() {
		return this.codigoIso;
	}

	public void setCodigoIso(String codigoIso) {
		this.codigoIso = codigoIso;
	}

}
