package ni.com.sts.estudioCohorteCSSFV.modelo;

// Generated 26-feb-2015 20:57:39 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Diagnostico generated by hbm2java
 */
@Entity
@Table(name = "diagnostico", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "codigo_dignostico"))
public class Diagnostico implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8049347615426958913L;
	private int secDiagnostico;
	private short codigoDignostico;
	private String diagnostico;
	private char estado;

	public Diagnostico() {
	}

	public Diagnostico(int secDiagnostico, short codigoDignostico,
			String diagnostico, char estado) {
		this.secDiagnostico = secDiagnostico;
		this.codigoDignostico = codigoDignostico;
		this.diagnostico = diagnostico;
		this.estado = estado;
	}

	@Id
	@SequenceGenerator(name = "diagnostico_seq", sequenceName = "diagnostico_sec_diagnostico_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "diagnostico_seq")
	@Column(name = "sec_diagnostico", unique = true, nullable = false)
	public int getSecDiagnostico() {
		return this.secDiagnostico;
	}

	public void setSecDiagnostico(int secDiagnostico) {
		this.secDiagnostico = secDiagnostico;
	}

	@Column(name = "codigo_dignostico", unique = true, nullable = false)
	public short getCodigoDignostico() {
		return this.codigoDignostico;
	}

	public void setCodigoDignostico(short codigoDignostico) {
		this.codigoDignostico = codigoDignostico;
	}

	@Column(name = "diagnostico", nullable = false, length = 64)
	public String getDiagnostico() {
		return this.diagnostico;
	}

	public void setDiagnostico(String diagnostico) {
		this.diagnostico = diagnostico;
	}

	@Column(name = "estado", nullable = false, length = 1)
	public char getEstado() {
		return this.estado;
	}

	public void setEstado(char estado) {
		this.estado = estado;
	}

}
