package ni.com.sts.estudioCohorteCSSFV.modelo;

// Generated 26-feb-2015 20:57:39 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;

/**
 * EghResultadosId generated by hbm2java
 */
@Embeddable
public class EghResultadosId implements java.io.Serializable {

	private int secEghResultado;
	private int secOrdenLaboratorio;
	private String color;
	private String consistencia;
	private String restosAlimenticios;
	private String mucus;
	private String ph;
	private String sangreOculta;
	private String bacterias;
	private String levaduras;
	private String leucocitos;
	private String eritrocitos;
	private String filamentosMucosos;
	private String EColi;
	private String endolimaxNana;
	private String EHistolytica;
	private String gardiaAmblia;
	private String trichuris;
	private String hymenolepisNana;
	private String strongyloideStercolaris;
	private String unicinarias;
	private String enterovirus;
	private String observaciones;
	private String codigoMuestra;
	private Short usuarioBionalista;
	private Date horaReporte;
	private Character estado;

	public EghResultadosId() {
	}

	public EghResultadosId(int secEghResultado, int secOrdenLaboratorio) {
		this.secEghResultado = secEghResultado;
		this.secOrdenLaboratorio = secOrdenLaboratorio;
	}

	public EghResultadosId(int secEghResultado, int secOrdenLaboratorio,
			String color, String consistencia, String restosAlimenticios,
			String mucus, String ph, String sangreOculta, String bacterias,
			String levaduras, String leucocitos, String eritrocitos,
			String filamentosMucosos, String EColi, String endolimaxNana,
			String EHistolytica, String gardiaAmblia, String trichuris,
			String hymenolepisNana, String strongyloideStercolaris,
			String unicinarias, String enterovirus, String observaciones,
			String codigoMuestra, Short usuarioBionalista, Date horaReporte,
			Character estado) {
		this.secEghResultado = secEghResultado;
		this.secOrdenLaboratorio = secOrdenLaboratorio;
		this.color = color;
		this.consistencia = consistencia;
		this.restosAlimenticios = restosAlimenticios;
		this.mucus = mucus;
		this.ph = ph;
		this.sangreOculta = sangreOculta;
		this.bacterias = bacterias;
		this.levaduras = levaduras;
		this.leucocitos = leucocitos;
		this.eritrocitos = eritrocitos;
		this.filamentosMucosos = filamentosMucosos;
		this.EColi = EColi;
		this.endolimaxNana = endolimaxNana;
		this.EHistolytica = EHistolytica;
		this.gardiaAmblia = gardiaAmblia;
		this.trichuris = trichuris;
		this.hymenolepisNana = hymenolepisNana;
		this.strongyloideStercolaris = strongyloideStercolaris;
		this.unicinarias = unicinarias;
		this.enterovirus = enterovirus;
		this.observaciones = observaciones;
		this.codigoMuestra = codigoMuestra;
		this.usuarioBionalista = usuarioBionalista;
		this.horaReporte = horaReporte;
		this.estado = estado;
	}
	
	@Id
	@SequenceGenerator(name = "id_egh_resultado_sec", sequenceName = "egh_resultados_sec_egh_resultado_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "id_egh_resultado_sec")
	@Column(name = "sec_egh_resultado", unique = true, nullable = false)
	public int getSecEghResultado() {
		return this.secEghResultado;
	}

	public void setSecEghResultado(int secEghResultado) {
		this.secEghResultado = secEghResultado;
	}

	@Column(name = "sec_orden_laboratorio", nullable = false)
	public int getSecOrdenLaboratorio() {
		return this.secOrdenLaboratorio;
	}

	public void setSecOrdenLaboratorio(int secOrdenLaboratorio) {
		this.secOrdenLaboratorio = secOrdenLaboratorio;
	}

	@Column(name = "color", length = 32)
	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	@Column(name = "consistencia", length = 32)
	public String getConsistencia() {
		return this.consistencia;
	}

	public void setConsistencia(String consistencia) {
		this.consistencia = consistencia;
	}

	@Column(name = "restos_alimenticios", length = 32)
	public String getRestosAlimenticios() {
		return this.restosAlimenticios;
	}

	public void setRestosAlimenticios(String restosAlimenticios) {
		this.restosAlimenticios = restosAlimenticios;
	}

	@Column(name = "mucus", length = 32)
	public String getMucus() {
		return this.mucus;
	}

	public void setMucus(String mucus) {
		this.mucus = mucus;
	}

	@Column(name = "ph", length = 32)
	public String getPh() {
		return this.ph;
	}

	public void setPh(String ph) {
		this.ph = ph;
	}

	@Column(name = "sangre_oculta", length = 32)
	public String getSangreOculta() {
		return this.sangreOculta;
	}

	public void setSangreOculta(String sangreOculta) {
		this.sangreOculta = sangreOculta;
	}

	@Column(name = "bacterias", length = 32)
	public String getBacterias() {
		return this.bacterias;
	}

	public void setBacterias(String bacterias) {
		this.bacterias = bacterias;
	}

	@Column(name = "levaduras", length = 32)
	public String getLevaduras() {
		return this.levaduras;
	}

	public void setLevaduras(String levaduras) {
		this.levaduras = levaduras;
	}

	@Column(name = "leucocitos", length = 32)
	public String getLeucocitos() {
		return this.leucocitos;
	}

	public void setLeucocitos(String leucocitos) {
		this.leucocitos = leucocitos;
	}

	@Column(name = "eritrocitos", length = 32)
	public String getEritrocitos() {
		return this.eritrocitos;
	}

	public void setEritrocitos(String eritrocitos) {
		this.eritrocitos = eritrocitos;
	}

	@Column(name = "filamentos_mucosos", length = 32)
	public String getFilamentosMucosos() {
		return this.filamentosMucosos;
	}

	public void setFilamentosMucosos(String filamentosMucosos) {
		this.filamentosMucosos = filamentosMucosos;
	}

	@Column(name = "e_coli", length = 32)
	public String getEColi() {
		return this.EColi;
	}

	public void setEColi(String EColi) {
		this.EColi = EColi;
	}

	@Column(name = "endolimax_nana", length = 32)
	public String getEndolimaxNana() {
		return this.endolimaxNana;
	}

	public void setEndolimaxNana(String endolimaxNana) {
		this.endolimaxNana = endolimaxNana;
	}

	@Column(name = "e_histolytica", length = 32)
	public String getEHistolytica() {
		return this.EHistolytica;
	}

	public void setEHistolytica(String EHistolytica) {
		this.EHistolytica = EHistolytica;
	}

	@Column(name = "gardia_amblia", length = 32)
	public String getGardiaAmblia() {
		return this.gardiaAmblia;
	}

	public void setGardiaAmblia(String gardiaAmblia) {
		this.gardiaAmblia = gardiaAmblia;
	}

	@Column(name = "trichuris", length = 32)
	public String getTrichuris() {
		return this.trichuris;
	}

	public void setTrichuris(String trichuris) {
		this.trichuris = trichuris;
	}

	@Column(name = "hymenolepis_nana", length = 32)
	public String getHymenolepisNana() {
		return this.hymenolepisNana;
	}

	public void setHymenolepisNana(String hymenolepisNana) {
		this.hymenolepisNana = hymenolepisNana;
	}

	@Column(name = "strongyloide_stercolaris", length = 32)
	public String getStrongyloideStercolaris() {
		return this.strongyloideStercolaris;
	}

	public void setStrongyloideStercolaris(String strongyloideStercolaris) {
		this.strongyloideStercolaris = strongyloideStercolaris;
	}

	@Column(name = "unicinarias", length = 32)
	public String getUnicinarias() {
		return this.unicinarias;
	}

	public void setUnicinarias(String unicinarias) {
		this.unicinarias = unicinarias;
	}

	@Column(name = "enterovirus", length = 32)
	public String getEnterovirus() {
		return this.enterovirus;
	}

	public void setEnterovirus(String enterovirus) {
		this.enterovirus = enterovirus;
	}

	@Column(name = "observaciones", length = 64)
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	@Column(name = "codigo_muestra", length = 50)
	public String getCodigoMuestra() {
		return this.codigoMuestra;
	}

	public void setCodigoMuestra(String codigoMuestra) {
		this.codigoMuestra = codigoMuestra;
	}

	@Column(name = "usuario_bionalista")
	public Short getUsuarioBionalista() {
		return this.usuarioBionalista;
	}

	public void setUsuarioBionalista(Short usuarioBionalista) {
		this.usuarioBionalista = usuarioBionalista;
	}

	@Column(name = "hora_reporte", length = 29)
	public Date getHoraReporte() {
		return this.horaReporte;
	}

	public void setHoraReporte(Date horaReporte) {
		this.horaReporte = horaReporte;
	}

	@Column(name = "estado", length = 1)
	public Character getEstado() {
		return this.estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EghResultadosId))
			return false;
		EghResultadosId castOther = (EghResultadosId) other;

		return (this.getSecEghResultado() == castOther.getSecEghResultado())
				&& (this.getSecOrdenLaboratorio() == castOther
						.getSecOrdenLaboratorio())
				&& ((this.getColor() == castOther.getColor()) || (this
						.getColor() != null && castOther.getColor() != null && this
						.getColor().equals(castOther.getColor())))
				&& ((this.getConsistencia() == castOther.getConsistencia()) || (this
						.getConsistencia() != null
						&& castOther.getConsistencia() != null && this
						.getConsistencia().equals(castOther.getConsistencia())))
				&& ((this.getRestosAlimenticios() == castOther
						.getRestosAlimenticios()) || (this
						.getRestosAlimenticios() != null
						&& castOther.getRestosAlimenticios() != null && this
						.getRestosAlimenticios().equals(
								castOther.getRestosAlimenticios())))
				&& ((this.getMucus() == castOther.getMucus()) || (this
						.getMucus() != null && castOther.getMucus() != null && this
						.getMucus().equals(castOther.getMucus())))
				&& ((this.getPh() == castOther.getPh()) || (this.getPh() != null
						&& castOther.getPh() != null && this.getPh().equals(
						castOther.getPh())))
				&& ((this.getSangreOculta() == castOther.getSangreOculta()) || (this
						.getSangreOculta() != null
						&& castOther.getSangreOculta() != null && this
						.getSangreOculta().equals(castOther.getSangreOculta())))
				&& ((this.getBacterias() == castOther.getBacterias()) || (this
						.getBacterias() != null
						&& castOther.getBacterias() != null && this
						.getBacterias().equals(castOther.getBacterias())))
				&& ((this.getLevaduras() == castOther.getLevaduras()) || (this
						.getLevaduras() != null
						&& castOther.getLevaduras() != null && this
						.getLevaduras().equals(castOther.getLevaduras())))
				&& ((this.getLeucocitos() == castOther.getLeucocitos()) || (this
						.getLeucocitos() != null
						&& castOther.getLeucocitos() != null && this
						.getLeucocitos().equals(castOther.getLeucocitos())))
				&& ((this.getEritrocitos() == castOther.getEritrocitos()) || (this
						.getEritrocitos() != null
						&& castOther.getEritrocitos() != null && this
						.getEritrocitos().equals(castOther.getEritrocitos())))
				&& ((this.getFilamentosMucosos() == castOther
						.getFilamentosMucosos()) || (this
						.getFilamentosMucosos() != null
						&& castOther.getFilamentosMucosos() != null && this
						.getFilamentosMucosos().equals(
								castOther.getFilamentosMucosos())))
				&& ((this.getEColi() == castOther.getEColi()) || (this
						.getEColi() != null && castOther.getEColi() != null && this
						.getEColi().equals(castOther.getEColi())))
				&& ((this.getEndolimaxNana() == castOther.getEndolimaxNana()) || (this
						.getEndolimaxNana() != null
						&& castOther.getEndolimaxNana() != null && this
						.getEndolimaxNana()
						.equals(castOther.getEndolimaxNana())))
				&& ((this.getEHistolytica() == castOther.getEHistolytica()) || (this
						.getEHistolytica() != null
						&& castOther.getEHistolytica() != null && this
						.getEHistolytica().equals(castOther.getEHistolytica())))
				&& ((this.getGardiaAmblia() == castOther.getGardiaAmblia()) || (this
						.getGardiaAmblia() != null
						&& castOther.getGardiaAmblia() != null && this
						.getGardiaAmblia().equals(castOther.getGardiaAmblia())))
				&& ((this.getTrichuris() == castOther.getTrichuris()) || (this
						.getTrichuris() != null
						&& castOther.getTrichuris() != null && this
						.getTrichuris().equals(castOther.getTrichuris())))
				&& ((this.getHymenolepisNana() == castOther
						.getHymenolepisNana()) || (this.getHymenolepisNana() != null
						&& castOther.getHymenolepisNana() != null && this
						.getHymenolepisNana().equals(
								castOther.getHymenolepisNana())))
				&& ((this.getStrongyloideStercolaris() == castOther
						.getStrongyloideStercolaris()) || (this
						.getStrongyloideStercolaris() != null
						&& castOther.getStrongyloideStercolaris() != null && this
						.getStrongyloideStercolaris().equals(
								castOther.getStrongyloideStercolaris())))
				&& ((this.getUnicinarias() == castOther.getUnicinarias()) || (this
						.getUnicinarias() != null
						&& castOther.getUnicinarias() != null && this
						.getUnicinarias().equals(castOther.getUnicinarias())))
				&& ((this.getEnterovirus() == castOther.getEnterovirus()) || (this
						.getEnterovirus() != null
						&& castOther.getEnterovirus() != null && this
						.getEnterovirus().equals(castOther.getEnterovirus())))
				&& ((this.getObservaciones() == castOther.getObservaciones()) || (this
						.getObservaciones() != null
						&& castOther.getObservaciones() != null && this
						.getObservaciones()
						.equals(castOther.getObservaciones())))
				&& ((this.getCodigoMuestra() == castOther.getCodigoMuestra()) || (this
						.getCodigoMuestra() != null
						&& castOther.getCodigoMuestra() != null && this
						.getCodigoMuestra()
						.equals(castOther.getCodigoMuestra())))
				&& ((this.getUsuarioBionalista() == castOther
						.getUsuarioBionalista()) || (this
						.getUsuarioBionalista() != null
						&& castOther.getUsuarioBionalista() != null && this
						.getUsuarioBionalista().equals(
								castOther.getUsuarioBionalista())))
				&& ((this.getHoraReporte() == castOther.getHoraReporte()) || (this
						.getHoraReporte() != null
						&& castOther.getHoraReporte() != null && this
						.getHoraReporte().equals(castOther.getHoraReporte())))
				&& ((this.getEstado() == castOther.getEstado()) || (this
						.getEstado() != null && castOther.getEstado() != null && this
						.getEstado().equals(castOther.getEstado())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSecEghResultado();
		result = 37 * result + this.getSecOrdenLaboratorio();
		result = 37 * result
				+ (getColor() == null ? 0 : this.getColor().hashCode());
		result = 37
				* result
				+ (getConsistencia() == null ? 0 : this.getConsistencia()
						.hashCode());
		result = 37
				* result
				+ (getRestosAlimenticios() == null ? 0 : this
						.getRestosAlimenticios().hashCode());
		result = 37 * result
				+ (getMucus() == null ? 0 : this.getMucus().hashCode());
		result = 37 * result + (getPh() == null ? 0 : this.getPh().hashCode());
		result = 37
				* result
				+ (getSangreOculta() == null ? 0 : this.getSangreOculta()
						.hashCode());
		result = 37 * result
				+ (getBacterias() == null ? 0 : this.getBacterias().hashCode());
		result = 37 * result
				+ (getLevaduras() == null ? 0 : this.getLevaduras().hashCode());
		result = 37
				* result
				+ (getLeucocitos() == null ? 0 : this.getLeucocitos()
						.hashCode());
		result = 37
				* result
				+ (getEritrocitos() == null ? 0 : this.getEritrocitos()
						.hashCode());
		result = 37
				* result
				+ (getFilamentosMucosos() == null ? 0 : this
						.getFilamentosMucosos().hashCode());
		result = 37 * result
				+ (getEColi() == null ? 0 : this.getEColi().hashCode());
		result = 37
				* result
				+ (getEndolimaxNana() == null ? 0 : this.getEndolimaxNana()
						.hashCode());
		result = 37
				* result
				+ (getEHistolytica() == null ? 0 : this.getEHistolytica()
						.hashCode());
		result = 37
				* result
				+ (getGardiaAmblia() == null ? 0 : this.getGardiaAmblia()
						.hashCode());
		result = 37 * result
				+ (getTrichuris() == null ? 0 : this.getTrichuris().hashCode());
		result = 37
				* result
				+ (getHymenolepisNana() == null ? 0 : this.getHymenolepisNana()
						.hashCode());
		result = 37
				* result
				+ (getStrongyloideStercolaris() == null ? 0 : this
						.getStrongyloideStercolaris().hashCode());
		result = 37
				* result
				+ (getUnicinarias() == null ? 0 : this.getUnicinarias()
						.hashCode());
		result = 37
				* result
				+ (getEnterovirus() == null ? 0 : this.getEnterovirus()
						.hashCode());
		result = 37
				* result
				+ (getObservaciones() == null ? 0 : this.getObservaciones()
						.hashCode());
		result = 37
				* result
				+ (getCodigoMuestra() == null ? 0 : this.getCodigoMuestra()
						.hashCode());
		result = 37
				* result
				+ (getUsuarioBionalista() == null ? 0 : this
						.getUsuarioBionalista().hashCode());
		result = 37
				* result
				+ (getHoraReporte() == null ? 0 : this.getHoraReporte()
						.hashCode());
		result = 37 * result
				+ (getEstado() == null ? 0 : this.getEstado().hashCode());
		return result;
	}

}
