package ni.com.sts.estudioCohorteCSSFV.modelo;

// Generated 26-feb-2015 20:57:39 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EgoResultados generated by hbm2java
 */
@Entity
@Table(name = "ego_resultados", schema = "public")
public class EgoResultados implements java.io.Serializable {

	private int secEgoResultado;
	private OrdenLaboratorio ordenLaboratorio;
	private String color;
	private String aspecto;
	private String sedimento;
	private String densidad;
	private String proteinas;
	private String homoglobinas;
	private String cuerpoCetonico;
	private String ph;
	private String urobilinogeno;
	private String glucosa;
	private String bilirrubinas;
	private String nitritos;
	private String celulasEpiteliales;
	private String leucositos;
	private String eritrocitos;
	private String cilindros;
	private String cristales;
	private String hilosMucosos;
	private String bacterias;
	private String levaduras;
	private String observaciones;
	private String codigoMuestra;
	private Short usuarioBioanalista;
	private Date horaReporte;
	private Character estado;

	public EgoResultados() {
	}

	public EgoResultados(int secEgoResultado, OrdenLaboratorio ordenLaboratorio) {
		this.secEgoResultado = secEgoResultado;
		this.ordenLaboratorio = ordenLaboratorio;
	}

	public EgoResultados(int secEgoResultado,
			OrdenLaboratorio ordenLaboratorio, String color, String aspecto,
			String sedimento, String densidad, String proteinas,
			String homoglobinas, String cuerpoCetonico, String ph,
			String urobilinogeno, String glucosa, String bilirrubinas,
			String nitritos, String celulasEpiteliales, String leucositos,
			String eritrocitos, String cilindros, String cristales,
			String hilosMucosos, String bacterias, String levaduras,
			String observaciones, String codigoMuestra,
			Short usuarioBioanalista, Date horaReporte, Character estado) {
		this.secEgoResultado = secEgoResultado;
		this.ordenLaboratorio = ordenLaboratorio;
		this.color = color;
		this.aspecto = aspecto;
		this.sedimento = sedimento;
		this.densidad = densidad;
		this.proteinas = proteinas;
		this.homoglobinas = homoglobinas;
		this.cuerpoCetonico = cuerpoCetonico;
		this.ph = ph;
		this.urobilinogeno = urobilinogeno;
		this.glucosa = glucosa;
		this.bilirrubinas = bilirrubinas;
		this.nitritos = nitritos;
		this.celulasEpiteliales = celulasEpiteliales;
		this.leucositos = leucositos;
		this.eritrocitos = eritrocitos;
		this.cilindros = cilindros;
		this.cristales = cristales;
		this.hilosMucosos = hilosMucosos;
		this.bacterias = bacterias;
		this.levaduras = levaduras;
		this.observaciones = observaciones;
		this.codigoMuestra = codigoMuestra;
		this.usuarioBioanalista = usuarioBioanalista;
		this.horaReporte = horaReporte;
		this.estado = estado;
	}

	@Id
	@SequenceGenerator(name = "id_ego_resultado_sec", sequenceName = "ego_resultados_sec_ego_resultado_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "id_ego_resultado_sec")
	@Column(name = "sec_ego_resultado", unique = true, nullable = false)
	public int getSecEgoResultado() {
		return this.secEgoResultado;
	}

	public void setSecEgoResultado(int secEgoResultado) {
		this.secEgoResultado = secEgoResultado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sec_orden_laboratorio", nullable = false)
	public OrdenLaboratorio getOrdenLaboratorio() {
		return this.ordenLaboratorio;
	}

	public void setOrdenLaboratorio(OrdenLaboratorio ordenLaboratorio) {
		this.ordenLaboratorio = ordenLaboratorio;
	}

	@Column(name = "color", length = 32)
	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	@Column(name = "aspecto", length = 32)
	public String getAspecto() {
		return this.aspecto;
	}

	public void setAspecto(String aspecto) {
		this.aspecto = aspecto;
	}

	@Column(name = "sedimento", length = 32)
	public String getSedimento() {
		return this.sedimento;
	}

	public void setSedimento(String sedimento) {
		this.sedimento = sedimento;
	}

	@Column(name = "densidad", length = 32)
	public String getDensidad() {
		return this.densidad;
	}

	public void setDensidad(String densidad) {
		this.densidad = densidad;
	}

	@Column(name = "proteinas", length = 32)
	public String getProteinas() {
		return this.proteinas;
	}

	public void setProteinas(String proteinas) {
		this.proteinas = proteinas;
	}

	@Column(name = "homoglobinas", length = 32)
	public String getHomoglobinas() {
		return this.homoglobinas;
	}

	public void setHomoglobinas(String homoglobinas) {
		this.homoglobinas = homoglobinas;
	}

	@Column(name = "cuerpo_cetonico", length = 32)
	public String getCuerpoCetonico() {
		return this.cuerpoCetonico;
	}

	public void setCuerpoCetonico(String cuerpoCetonico) {
		this.cuerpoCetonico = cuerpoCetonico;
	}

	@Column(name = "ph", length = 32)
	public String getPh() {
		return this.ph;
	}

	public void setPh(String ph) {
		this.ph = ph;
	}

	@Column(name = "urobilinogeno", length = 32)
	public String getUrobilinogeno() {
		return this.urobilinogeno;
	}

	public void setUrobilinogeno(String urobilinogeno) {
		this.urobilinogeno = urobilinogeno;
	}

	@Column(name = "glucosa", length = 32)
	public String getGlucosa() {
		return this.glucosa;
	}

	public void setGlucosa(String glucosa) {
		this.glucosa = glucosa;
	}

	@Column(name = "bilirrubinas", length = 32)
	public String getBilirrubinas() {
		return this.bilirrubinas;
	}

	public void setBilirrubinas(String bilirrubinas) {
		this.bilirrubinas = bilirrubinas;
	}

	@Column(name = "nitritos", length = 32)
	public String getNitritos() {
		return this.nitritos;
	}

	public void setNitritos(String nitritos) {
		this.nitritos = nitritos;
	}

	@Column(name = "celulas_epiteliales", length = 32)
	public String getCelulasEpiteliales() {
		return this.celulasEpiteliales;
	}

	public void setCelulasEpiteliales(String celulasEpiteliales) {
		this.celulasEpiteliales = celulasEpiteliales;
	}

	@Column(name = "leucositos", length = 32)
	public String getLeucositos() {
		return this.leucositos;
	}

	public void setLeucositos(String leucositos) {
		this.leucositos = leucositos;
	}

	@Column(name = "eritrocitos", length = 32)
	public String getEritrocitos() {
		return this.eritrocitos;
	}

	public void setEritrocitos(String eritrocitos) {
		this.eritrocitos = eritrocitos;
	}

	@Column(name = "cilindros", length = 32)
	public String getCilindros() {
		return this.cilindros;
	}

	public void setCilindros(String cilindros) {
		this.cilindros = cilindros;
	}

	@Column(name = "cristales", length = 32)
	public String getCristales() {
		return this.cristales;
	}

	public void setCristales(String cristales) {
		this.cristales = cristales;
	}

	@Column(name = "hilos_mucosos", length = 32)
	public String getHilosMucosos() {
		return this.hilosMucosos;
	}

	public void setHilosMucosos(String hilosMucosos) {
		this.hilosMucosos = hilosMucosos;
	}

	@Column(name = "bacterias", length = 32)
	public String getBacterias() {
		return this.bacterias;
	}

	public void setBacterias(String bacterias) {
		this.bacterias = bacterias;
	}

	@Column(name = "levaduras", length = 32)
	public String getLevaduras() {
		return this.levaduras;
	}

	public void setLevaduras(String levaduras) {
		this.levaduras = levaduras;
	}

	@Column(name = "observaciones", length = 64)
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	@Column(name = "codigo_muestra", length = 50)
	public String getCodigoMuestra() {
		return this.codigoMuestra;
	}

	public void setCodigoMuestra(String codigoMuestra) {
		this.codigoMuestra = codigoMuestra;
	}

	@Column(name = "usuario_bioanalista")
	public Short getUsuarioBioanalista() {
		return this.usuarioBioanalista;
	}

	public void setUsuarioBioanalista(Short usuarioBioanalista) {
		this.usuarioBioanalista = usuarioBioanalista;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "hora_reporte", length = 29)
	public Date getHoraReporte() {
		return this.horaReporte;
	}

	public void setHoraReporte(Date horaReporte) {
		this.horaReporte = horaReporte;
	}

	@Column(name = "estado", length = 1)
	public Character getEstado() {
		return this.estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

}
