package ni.com.sts.estudioCohorteCSSFV.modelo;

// Generated 26-feb-2015 20:57:39 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Admision generated by hbm2java
 */
@Entity
@Table(name = "escuela_catalogo", schema = "public")
public class EscuelaCatalogo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1725028971303877455L;
	private int codEscuela;
	private String descripcion;

	public EscuelaCatalogo() {
	}

	public EscuelaCatalogo(int codEstudio, String descEstudio) {
		this.codEscuela = codEstudio;
		this.descripcion = descEstudio;
	}


	@Id
	@Column(name = "cod_escuela", nullable = false)
	public int getCodEscuela() {
		return this.codEscuela;
	}

	public void setCodEscuela(int codEscuela) {
		this.codEscuela = codEscuela;
	}

	@Column(name = "descripcion", nullable = false, length = 16)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
}
