package ni.com.sts.estudioCohorteCSSFV.modelo;

// Generated 26-feb-2015 20:57:39 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * EstadosHoja generated by hbm2java
 */
@Entity
@Table(name = "estados_hoja", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "sec_estado"))
public class EstadosHoja implements java.io.Serializable {

	private char codigo;
	private int secEstado;
	private String descripcion;
	private char estado;
	private int orden;

	public EstadosHoja() {
	}

	public EstadosHoja(char codigo, int secEstado, String descripcion,
			char estado, int orden) {
		this.codigo = codigo;
		this.secEstado = secEstado;
		this.descripcion = descripcion;
		this.estado = estado;
		this.orden = orden;
	}

	@Id
	@Column(name = "codigo", unique = true, nullable = false, length = 1)
	public char getCodigo() {
		return this.codigo;
	}

	public void setCodigo(char codigo) {
		this.codigo = codigo;
	}

	@Column(name = "sec_estado", unique = true, nullable = false)
	public int getSecEstado() {
		return this.secEstado;
	}

	public void setSecEstado(int secEstado) {
		this.secEstado = secEstado;
	}

	@Column(name = "descripcion", nullable = false, length = 16)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "estado", nullable = false, length = 1)
	public char getEstado() {
		return this.estado;
	}

	public void setEstado(char estado) {
		this.estado = estado;
	}

	@Column(name = "orden", nullable = true)
	public int getOrden() {
		return orden;
	}

	public void setOrden(int orden) {
		this.orden = orden;
	}
}
