package ni.com.sts.estudioCohorteCSSFV.modelo;

// Generated 26-feb-2015 20:57:39 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Admision generated by hbm2java
 */
@Entity
@Table(name = "estudio_catalogo", schema = "public")
public class EstudioCatalogo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1725028971303877455L;
	private int codEstudio;
	private String descEstudio;

	public EstudioCatalogo() {
	}

	public EstudioCatalogo(int codEstudio, String descEstudio) {
		this.codEstudio = codEstudio;
		this.descEstudio = descEstudio;
	}


	@Id
	@Column(name = "cod_estudio", nullable = false)
	public int getCodEstudio() {
		return this.codEstudio;
	}

	public void setCodEstudio(int codEstudio) {
		this.codEstudio = codEstudio;
	}

	@Column(name = "desc_estudio", nullable = false, length = 16)
	public String getDescEstudio() {
		return this.descEstudio;
	}

	public void setDescEstudio(String descEstudio) {
		this.descEstudio = descEstudio;
	}
}
