package ni.com.sts.estudioCohorteCSSFV.modelo;

// Generated Oct 2, 2015 2:04:34 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HojaConsulta generated by hbm2java
 */
@Entity
@Table(name = "hoja_consulta")
public class HojaConsulta implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int secHojaConsulta;
	private int codExpediente;
	private int numHojaConsulta;
	private short ordenLlegada;
	private char estado;
	private Date fechaConsulta;
	private Short usuarioEnfermeria;
	private Short usuarioMedico;
	private BigDecimal pesoKg;
	private BigDecimal tallaCm;
	private BigDecimal temperaturac;
	private Integer presion;
	private Short fciaResp;
	private Short fciaCard;
	private String lugarAtencion;
	private String consulta;
	private Character segChick;
	private Character turno;
	private BigDecimal temMedc;
	private Date ultDiaFiebre;
	private Date ultDosisAntipiretico;
	private Character fiebre;
	private Character astenia;
	private Character asomnoliento;
	private Character malEstado;
	private Character perdidaConsciencia;
	private Character inquieto;
	private Character convulsiones;
	private Character hipotermia;
	private Character letargia;
	private Character cefalea;
	private Character rigidezCuello;
	private Character inyeccionConjuntival;
	private Character hemorragiaSuconjuntival;
	private Character dolorRetroocular;
	private Character fontanelaAbombada;
	private Character ictericiaConuntival;
	private Character eritema;
	private Character dolorGarganta;
	private Character adenopatiasCervicales;
	private Character exudado;
	private Character petequiasMucosa;
	private Character tos;
	private Character rinorrea;
	private Character congestionNasal;
	private Character otalgia;
	private Character aleteoNasal;
	private Character apnea;
	private Character respiracionRapida;
	private Character quejidoEspiratorio;
	private Character estiradorReposo;
	private Character tirajeSubcostal;
	private Character sibilancias;
	private Character crepitos;
	private Character roncos;
	private Character otraFif;
	private Date nuevaFif;
	private Character pocoApetito;
	private Character nausea;
	private Character dificultadAlimentarse;
	private Character vomito12horas;
	private Character diarrea;
	private Character diarreaSangre;
	private Character estrenimiento;
	private Character dolorAbIntermitente;
	private Character dolorAbContinuo;
	private Character epigastralgia;
	private Character intoleranciaOral;
	private Character distensionAbdominal;
	private Character hepatomegalia;
	private Character lenguaMucosasSecas;
	private Character pliegueCutaneo;
	private Character orinaReducida;
	private Character bebeConSed;
	private String ojosHundidos;
	private Character fontanelaHundida;
	private Character sintomasUrinarios;
	private Character leucocituria;
	private Character nitritos;
	private Character bilirrubinuria;
	private Character altralgia;
	private Character mialgia;
	private Character lumbalgia;
	private Character dolorCuello;
	private Character tenosinovitis;
	private Character artralgiaProximal;
	private Character artralgiaDistal;
	private Character conjuntivitis;
	private Character edemaMunecas;
	private Character edemaCodos;
	private Character edemaHombros;
	private Character edemaRodillas;
	private Character edemaTobillos;
	private Character rahsLocalizado;
	private Character rahsGeneralizado;
	private Character rashEritematoso;
	private Character rahsMacular;
	private Character rashPapular;
	private Character rahsMoteada;
	private Character ruborFacial;
	private Character equimosis;
	private Character cianosisCentral;
	private Character ictericia;
	private Character obeso;
	private Character sobrepeso;
	private Character sospechaProblema;
	private Character normal;
	private Character bajoPeso;
	private Character bajoPesoSevero;
	private Character lactanciaMaterna;
	private Character vacunasCompletas;
	private Character vacunaInfluenza;
	private Date fechaVacuna;
	private Character interconsultaPediatrica;
	private Character referenciaHospital;
	private Character referenciaDengue;
	private Character referenciaIrag;
	private Character referenciaChik;
	private Character eti;
	private Character irag;
	private Character neumonia;
	private Short saturaciono2;
	private BigDecimal imc;
	private String categoria;
	private Character cambioCategoria;
	private Character manifestacionHemorragica;
	private Character pruebaTorniquetePositiva;
	private Character petequia10Pt;
	private Character petequia20Pt;
	private Character pielExtremidadesFrias;
	private Character palidezEnExtremidades;
	private Character epistaxis;
	private Character gingivorragia;
	private Character petequiasEspontaneas;
	private Character llenadoCapilar2seg;
	private Character cianosis;
	private BigDecimal linfocitosaAtipicos;
	private Date fechaLinfocitos;
	private Character hipermenorrea;
	private Character hematemesis;
	private Character melena;
	private Short hemoconcentracion;
	private Character hospitalizado;
	private String hospitalizadoEspecificar;
	private Character transfusionSangre;
	private String transfusionEspecificar;
	private Character tomandoMedicamento;
	private String medicamentoEspecificar;
	private Character medicamentoDistinto;
	private String medicamentoDistEspecificar;
	private Character bhc;
	private Character serologiaDengue;
	private Character serologiaChik;
	private Character gotaGruesa;
	private Character extendidoPeriferico;
	private Character ego;
	private Character egh;
	private Character citologiaFecal;
	private Character factorReumatoideo;
	private Character albumina;
	private Character astAlt;
	private Character bilirrubinas;
	private Character cpk;
	private Character colesterol;
	private Character influenza;
	private String otroExamenLab;
	private Character oel;	

	private Integer numOrdenLaboratorio;
	private Character acetaminofen;
	private Character asa;
	private Character ibuprofen;
	private Character penicilina;
	private Character amoxicilina;
	private Character dicloxacilina;
	private String otroAntibiotico;
	private Character furazolidona;
	private Character metronidazolTinidazol;
	private Character albendazolMebendazol;
	private Character sulfatoFerroso;
	private Character sueroOral;
	private Character sulfatoZinc;
	private Character liquidosIv;
	private Character prednisona;
	private Character hidrocortisonaIv;
	private Character salbutamol;
	private Character oseltamivir;
	private String historiaExamenFisico;
	private Short diagnostico1;
	private Short diagnostico2;
	private Short diagnostico3;
	private Short diagnostico4;
	private String otroDiagnostico;
	private Date proximaCita;
	private String horarioClases;
	private Date fechaCierre;
	private Date fechaCambioTurno;
	private Date fechaCierreCambioTurno;
	private String amPmUltDiaFiebre;
	private Date horaUltDosisAntipiretico;
	private String amPmUltDosisAntipiretico;
	private String expedienteFisico;
	private String colegio;
	private Date fechaOrdenLaboratorio;
	private Character estadoCarga;
	private Character otro;
	private Date fis;
	private Date fif;
	private BigDecimal hepatomegaliaCm;
	private Character eritrocitos;
	private String planes;
	private Short medicoCambioTurno;
	private Character hemoconc;
	private Short vomito12h;
	private Short pad;
	private Short pas;
	private Long telef;
	private String hora;
	private String horasv;
	
	private String noAtiendeLlamadoEnfermeria;
	private String noAtiendeLlamadoMedico;
	
	private String estudiosParticipantes;
	private boolean uaf;
	
	private String repeatKey; // 07/02/2020 dia en que se agrego
	
	private Character cV; // 05/06/2020
	
	private Character consultaRespiratorio; // 27/11/2020
	
	private Short usuarioCierraHoja; // 27/09/2021
	private Character hojaImpresa; // 27/09/2021
	
	private boolean digitada;
	private Short supervisor;
	private boolean offline;
	
	public HojaConsulta() {
	}

	public HojaConsulta(int secHojaConsulta, int codExpediente,
			int numHojaConsulta, short ordenLlegada, char estado,
			Date fechaConsulta, Short usuarioEnfermeria) {
		this.secHojaConsulta = secHojaConsulta;
		this.codExpediente = codExpediente;
		this.numHojaConsulta = numHojaConsulta;
		this.ordenLlegada = ordenLlegada;
		this.estado = estado;
		this.fechaConsulta = fechaConsulta;
		this.usuarioEnfermeria = usuarioEnfermeria;
	}

	public HojaConsulta(int secHojaConsulta, int codExpediente,
			int numHojaConsulta, short ordenLlegada, char estado,
			Date fechaConsulta, Short usuarioEnfermeria, Short usuarioMedico,
			BigDecimal pesoKg, BigDecimal tallaCm, BigDecimal temperaturac,
			Integer presion, Short fciaResp, Short fciaCard,
			String lugarAtencion, String consulta, Character segChick,
			Character turno, BigDecimal temMedc, Date ultDiaFiebre,
			Date ultDosisAntipiretico, Character fiebre, Character astenia,
			Character asomnoliento, Character malEstado,
			Character perdidaConsciencia, Character inquieto,
			Character convulsiones, Character hipotermia, Character letargia,
			Character cefalea, Character rigidezCuello,
			Character inyeccionConjuntival, Character hemorragiaSuconjuntival,
			Character dolorRetroocular, Character fontanelaAbombada,
			Character ictericiaConuntival, Character eritema,
			Character dolorGarganta, Character adenopatiasCervicales,
			Character exudado, Character petequiasMucosa, Character tos,
			Character rinorrea, Character congestionNasal, Character otalgia,
			Character aleteoNasal, Character apnea,
			Character respiracionRapida, Character quejidoEspiratorio,
			Character estiradorReposo, Character tirajeSubcostal,
			Character sibilancias, Character crepitos, Character roncos,
			Character otraFif, Date nuevaFif, Character pocoApetito,
			Character nausea, Character dificultadAlimentarse,
			Character vomito12horas, Character diarrea,
			Character diarreaSangre, Character estrenimiento,
			Character dolorAbIntermitente, Character dolorAbContinuo,
			Character epigastralgia, Character intoleranciaOral,
			Character distensionAbdominal, Character hepatomegalia,
			Character lenguaMucosasSecas, Character pliegueCutaneo,
			Character orinaReducida, Character bebeConSed, String ojosHundidos,
			Character fontanelaHundida, Character sintomasUrinarios,
			Character leucocituria, Character nitritos,
			Character bilirrubinuria, Character altralgia, Character mialgia,
			Character lumbalgia, Character dolorCuello,
			Character tenosinovitis, Character artralgiaProximal,
			Character artralgiaDistal, Character conjuntivitis,
			Character edemaMunecas, Character edemaCodos,
			Character edemaHombros, Character edemaRodillas,
			Character edemaTobillos, Character rahsLocalizado,
			Character rahsGeneralizado, Character rashEritematoso,
			Character rahsMacular, Character rashPapular,
			Character rahsMoteada, Character ruborFacial, Character equimosis,
			Character cianosisCentral, Character ictericia, Character obeso,
			Character sobrepeso, Character sospechaProblema, Character normal,
			Character bajoPeso, Character bajoPesoSevero,
			Character lactanciaMaterna, Character vacunasCompletas,
			Character vacunaInfluenza, Date fechaVacuna,
			Character interconsultaPediatrica, Character referenciaHospital,
			Character referenciaDengue, Character referenciaIrag,
			Character referenciaChik, Character eti, Character irag,
			Character neumonia, Short saturaciono2, BigDecimal imc,
			String categoria, Character cambioCategoria,
			Character manifestacionHemorragica,
			Character pruebaTorniquetePositiva, Character petequia10Pt,
			Character petequia20Pt, Character pielExtremidadesFrias,
			Character palidezEnExtremidades, Character epistaxis,
			Character gingivorragia, Character petequiasEspontaneas,
			Character llenadoCapilar2seg, Character cianosis,
			BigDecimal linfocitosaAtipicos, Date fechaLinfocitos,
			Character hipermenorrea, Character hematemesis, Character melena,
			Short hemoconcentracion, Character hospitalizado,
			String hospitalizadoEspecificar, Character transfusionSangre,
			String transfusionEspecificar, Character tomandoMedicamento,
			String medicamentoEspecificar, Character medicamentoDistinto,
			String medicamentoDistEspecificar, Character bhc,
			Character serologiaDengue, Character serologiaChik,
			Character gotaGruesa, Character extendidoPeriferico, Character ego,
			Character egh, Character citologiaFecal,
			Character factorReumatoideo, Character albumina, Character astAlt,
			Character bilirrubinas, Character cpk, Character colesterol,
			Character influenza, String otroExamenLab,
			Integer numOrdenLaboratorio, Character acetaminofen, Character asa,
			Character ibuprofen, Character penicilina, Character amoxicilina,
			Character dicloxacilina, String otroAntibiotico,
			Character furazolidona, Character metronidazolTinidazol,
			Character albendazolMebendazol, Character sulfatoFerroso,
			Character sueroOral, Character sulfatoZinc, Character liquidosIv,
			Character prednisona, Character hidrocortisonaIv,
			Character salbutamol, Character oseltamivir,
			String historiaExamenFisico, Short diagnostico1,
			Short diagnostico2, Short diagnostico3, Short diagnostico4,
			String otroDiagnostico, Date proximaCita, String horarioClases,
			Date fechaCierre, Date fechaCambioTurno,
			Date fechaCierreCambioTurno, String amPmUltDiaFiebre,
			Date horaUltDosisAntipiretico, String amPmUltDosisAntipiretico,
			String expedienteFisico, String colegio,
			Date fechaOrdenLaboratorio, Character estadoCarga, Character otro,
			Date fis, Date fif, BigDecimal hepatomegaliaCm,
			Character eritrocitos, String planes, Short medicoCambioTurno,
			Character hemoconc, Short vomito12h, Short pad, Short pas,
			Long telef, Character oel, String hora, String horasv, 
			String noAtiendeLlamadoEnfermeria, String noAtiendeLlamadoMedico, String estudiosParticipantes, boolean uaf,
			String repeatKey, Character cV, Character consultaRespiratorio, Short usuarioCierraHoja,
			Character hojaImpresa, boolean digitada, short supervisor, boolean offline) {
		this.secHojaConsulta = secHojaConsulta;
		this.codExpediente = codExpediente;
		this.numHojaConsulta = numHojaConsulta;
		this.ordenLlegada = ordenLlegada;
		this.estado = estado;
		this.fechaConsulta = fechaConsulta;
		this.usuarioEnfermeria = usuarioEnfermeria;
		this.usuarioMedico = usuarioMedico;
		this.pesoKg = pesoKg;
		this.tallaCm = tallaCm;
		this.temperaturac = temperaturac;
		this.presion = presion;
		this.fciaResp = fciaResp;
		this.fciaCard = fciaCard;
		this.lugarAtencion = lugarAtencion;
		this.consulta = consulta;
		this.segChick = segChick;
		this.turno = turno;
		this.temMedc = temMedc;
		this.ultDiaFiebre = ultDiaFiebre;
		this.ultDosisAntipiretico = ultDosisAntipiretico;
		this.fiebre = fiebre;
		this.astenia = astenia;
		this.asomnoliento = asomnoliento;
		this.malEstado = malEstado;
		this.perdidaConsciencia = perdidaConsciencia;
		this.inquieto = inquieto;
		this.convulsiones = convulsiones;
		this.hipotermia = hipotermia;
		this.letargia = letargia;
		this.cefalea = cefalea;
		this.rigidezCuello = rigidezCuello;
		this.inyeccionConjuntival = inyeccionConjuntival;
		this.hemorragiaSuconjuntival = hemorragiaSuconjuntival;
		this.dolorRetroocular = dolorRetroocular;
		this.fontanelaAbombada = fontanelaAbombada;
		this.ictericiaConuntival = ictericiaConuntival;
		this.eritema = eritema;
		this.dolorGarganta = dolorGarganta;
		this.adenopatiasCervicales = adenopatiasCervicales;
		this.exudado = exudado;
		this.petequiasMucosa = petequiasMucosa;
		this.tos = tos;
		this.rinorrea = rinorrea;
		this.congestionNasal = congestionNasal;
		this.otalgia = otalgia;
		this.aleteoNasal = aleteoNasal;
		this.apnea = apnea;
		this.respiracionRapida = respiracionRapida;
		this.quejidoEspiratorio = quejidoEspiratorio;
		this.estiradorReposo = estiradorReposo;
		this.tirajeSubcostal = tirajeSubcostal;
		this.sibilancias = sibilancias;
		this.crepitos = crepitos;
		this.roncos = roncos;
		this.otraFif = otraFif;
		this.nuevaFif = nuevaFif;
		this.pocoApetito = pocoApetito;
		this.nausea = nausea;
		this.dificultadAlimentarse = dificultadAlimentarse;
		this.vomito12horas = vomito12horas;
		this.diarrea = diarrea;
		this.diarreaSangre = diarreaSangre;
		this.estrenimiento = estrenimiento;
		this.dolorAbIntermitente = dolorAbIntermitente;
		this.dolorAbContinuo = dolorAbContinuo;
		this.epigastralgia = epigastralgia;
		this.intoleranciaOral = intoleranciaOral;
		this.distensionAbdominal = distensionAbdominal;
		this.hepatomegalia = hepatomegalia;
		this.lenguaMucosasSecas = lenguaMucosasSecas;
		this.pliegueCutaneo = pliegueCutaneo;
		this.orinaReducida = orinaReducida;
		this.bebeConSed = bebeConSed;
		this.ojosHundidos = ojosHundidos;
		this.fontanelaHundida = fontanelaHundida;
		this.sintomasUrinarios = sintomasUrinarios;
		this.leucocituria = leucocituria;
		this.nitritos = nitritos;
		this.bilirrubinuria = bilirrubinuria;
		this.altralgia = altralgia;
		this.mialgia = mialgia;
		this.lumbalgia = lumbalgia;
		this.dolorCuello = dolorCuello;
		this.tenosinovitis = tenosinovitis;
		this.artralgiaProximal = artralgiaProximal;
		this.artralgiaDistal = artralgiaDistal;
		this.conjuntivitis = conjuntivitis;
		this.edemaMunecas = edemaMunecas;
		this.edemaCodos = edemaCodos;
		this.edemaHombros = edemaHombros;
		this.edemaRodillas = edemaRodillas;
		this.edemaTobillos = edemaTobillos;
		this.rahsLocalizado = rahsLocalizado;
		this.rahsGeneralizado = rahsGeneralizado;
		this.rashEritematoso = rashEritematoso;
		this.rahsMacular = rahsMacular;
		this.rashPapular = rashPapular;
		this.rahsMoteada = rahsMoteada;
		this.ruborFacial = ruborFacial;
		this.equimosis = equimosis;
		this.cianosisCentral = cianosisCentral;
		this.ictericia = ictericia;
		this.obeso = obeso;
		this.sobrepeso = sobrepeso;
		this.sospechaProblema = sospechaProblema;
		this.normal = normal;
		this.bajoPeso = bajoPeso;
		this.bajoPesoSevero = bajoPesoSevero;
		this.lactanciaMaterna = lactanciaMaterna;
		this.vacunasCompletas = vacunasCompletas;
		this.vacunaInfluenza = vacunaInfluenza;
		this.fechaVacuna = fechaVacuna;
		this.interconsultaPediatrica = interconsultaPediatrica;
		this.referenciaHospital = referenciaHospital;
		this.referenciaDengue = referenciaDengue;
		this.referenciaIrag = referenciaIrag;
		this.referenciaChik = referenciaChik;
		this.eti = eti;
		this.irag = irag;
		this.neumonia = neumonia;
		this.saturaciono2 = saturaciono2;
		this.imc = imc;
		this.categoria = categoria;
		this.cambioCategoria = cambioCategoria;
		this.manifestacionHemorragica = manifestacionHemorragica;
		this.pruebaTorniquetePositiva = pruebaTorniquetePositiva;
		this.petequia10Pt = petequia10Pt;
		this.petequia20Pt = petequia20Pt;
		this.pielExtremidadesFrias = pielExtremidadesFrias;
		this.palidezEnExtremidades = palidezEnExtremidades;
		this.epistaxis = epistaxis;
		this.gingivorragia = gingivorragia;
		this.petequiasEspontaneas = petequiasEspontaneas;
		this.llenadoCapilar2seg = llenadoCapilar2seg;
		this.cianosis = cianosis;
		this.linfocitosaAtipicos = linfocitosaAtipicos;
		this.fechaLinfocitos = fechaLinfocitos;
		this.hipermenorrea = hipermenorrea;
		this.hematemesis = hematemesis;
		this.melena = melena;
		this.hemoconcentracion = hemoconcentracion;
		this.hospitalizado = hospitalizado;
		this.hospitalizadoEspecificar = hospitalizadoEspecificar;
		this.transfusionSangre = transfusionSangre;
		this.transfusionEspecificar = transfusionEspecificar;
		this.tomandoMedicamento = tomandoMedicamento;
		this.medicamentoEspecificar = medicamentoEspecificar;
		this.medicamentoDistinto = medicamentoDistinto;
		this.medicamentoDistEspecificar = medicamentoDistEspecificar;
		this.bhc = bhc;
		this.serologiaDengue = serologiaDengue;
		this.serologiaChik = serologiaChik;
		this.gotaGruesa = gotaGruesa;
		this.extendidoPeriferico = extendidoPeriferico;
		this.ego = ego;
		this.egh = egh;
		this.citologiaFecal = citologiaFecal;
		this.factorReumatoideo = factorReumatoideo;
		this.albumina = albumina;
		this.astAlt = astAlt;
		this.bilirrubinas = bilirrubinas;
		this.cpk = cpk;
		this.colesterol = colesterol;
		this.influenza = influenza;
		this.otroExamenLab = otroExamenLab;
		this.oel = oel;
		this.numOrdenLaboratorio = numOrdenLaboratorio;
		this.acetaminofen = acetaminofen;
		this.asa = asa;
		this.ibuprofen = ibuprofen;
		this.penicilina = penicilina;
		this.amoxicilina = amoxicilina;
		this.dicloxacilina = dicloxacilina;
		this.otroAntibiotico = otroAntibiotico;
		this.furazolidona = furazolidona;
		this.metronidazolTinidazol = metronidazolTinidazol;
		this.albendazolMebendazol = albendazolMebendazol;
		this.sulfatoFerroso = sulfatoFerroso;
		this.sueroOral = sueroOral;
		this.sulfatoZinc = sulfatoZinc;
		this.liquidosIv = liquidosIv;
		this.prednisona = prednisona;
		this.hidrocortisonaIv = hidrocortisonaIv;
		this.salbutamol = salbutamol;
		this.oseltamivir = oseltamivir;
		this.historiaExamenFisico = historiaExamenFisico;
		this.diagnostico1 = diagnostico1;
		this.diagnostico2 = diagnostico2;
		this.diagnostico3 = diagnostico3;
		this.diagnostico4 = diagnostico4;
		this.otroDiagnostico = otroDiagnostico;
		this.proximaCita = proximaCita;
		this.horarioClases = horarioClases;
		this.fechaCierre = fechaCierre;
		this.fechaCambioTurno = fechaCambioTurno;
		this.fechaCierreCambioTurno = fechaCierreCambioTurno;
		this.amPmUltDiaFiebre = amPmUltDiaFiebre;
		this.horaUltDosisAntipiretico = horaUltDosisAntipiretico;
		this.amPmUltDosisAntipiretico = amPmUltDosisAntipiretico;
		this.expedienteFisico = expedienteFisico;
		this.colegio = colegio;
		this.fechaOrdenLaboratorio = fechaOrdenLaboratorio;
		this.estadoCarga = estadoCarga;
		this.otro = otro;
		this.fis = fis;
		this.fif = fif;
		this.hepatomegaliaCm = hepatomegaliaCm;
		this.eritrocitos = eritrocitos;
		this.planes = planes;
		this.medicoCambioTurno = medicoCambioTurno;
		this.hemoconc = hemoconc;
		this.vomito12h = vomito12h;
		this.pad = pad;
		this.pas = pas;
		this.telef = telef;
		this.hora = hora;
		this.horasv = horasv;
		this.noAtiendeLlamadoEnfermeria = noAtiendeLlamadoEnfermeria;
		this.noAtiendeLlamadoMedico = noAtiendeLlamadoMedico;
		this.estudiosParticipantes = estudiosParticipantes;
		//this.setUaf(uaf);
		this.uaf = uaf;
		this.repeatKey = repeatKey;
		this.cV = cV;
		this.consultaRespiratorio = consultaRespiratorio;
		this.usuarioCierraHoja = usuarioCierraHoja;
		this.hojaImpresa = hojaImpresa;
		this.digitada = digitada;
		this.supervisor = supervisor;
		//this.setOffline(offline);
		this.offline = offline;

	}

	@Id
	@SequenceGenerator(name = "id_hoja_consulta_sec", sequenceName = "hoja_consulta_sec_hoja_consulta_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "id_hoja_consulta_sec")
	@Column(name = "sec_hoja_consulta", unique = true, nullable = false)
	public int getSecHojaConsulta() {
		return this.secHojaConsulta;
	}

	public void setSecHojaConsulta(int secHojaConsulta) {
		this.secHojaConsulta = secHojaConsulta;
	}

	@Column(name = "cod_expediente", nullable = false)
	public int getCodExpediente() {
		return this.codExpediente;
	}

	public void setCodExpediente(int codExpediente) {
		this.codExpediente = codExpediente;
	}

	@Column(name = "num_hoja_consulta", unique = true, nullable = false)
	public int getNumHojaConsulta() {
		return this.numHojaConsulta;
	}

	public void setNumHojaConsulta(int numHojaConsulta) {
		this.numHojaConsulta = numHojaConsulta;
	}

	@Column(name = "orden_llegada", nullable = false)
	public short getOrdenLlegada() {
		return this.ordenLlegada;
	}

	public void setOrdenLlegada(short ordenLlegada) {
		this.ordenLlegada = ordenLlegada;
	}

	@Column(name = "estado", nullable = false, length = 1)
	public char getEstado() {
		return this.estado;
	}

	public void setEstado(char estado) {
		this.estado = estado;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_consulta", nullable = false, length = 29)
	public Date getFechaConsulta() {
		return this.fechaConsulta;
	}

	public void setFechaConsulta(Date fechaConsulta) {
		this.fechaConsulta = fechaConsulta;
	}

	@Column(name = "usuario_enfermeria", nullable = true)
	public Short getUsuarioEnfermeria() {
		return this.usuarioEnfermeria;
	}

	public void setUsuarioEnfermeria(Short usuarioEnfermeria) {
		this.usuarioEnfermeria = usuarioEnfermeria;
	}

	@Column(name = "usuario_medico")
	public Short getUsuarioMedico() {
		return this.usuarioMedico;
	}

	public void setUsuarioMedico(Short usuarioMedico) {
		this.usuarioMedico = usuarioMedico;
	}

	@Column(name = "peso_kg", precision = 5)
	public BigDecimal getPesoKg() {
		return this.pesoKg;
	}

	public void setPesoKg(BigDecimal pesoKg) {
		this.pesoKg = pesoKg;
	}

	@Column(name = "talla_cm", precision = 5)
	public BigDecimal getTallaCm() {
		return this.tallaCm;
	}

	public void setTallaCm(BigDecimal tallaCm) {
		this.tallaCm = tallaCm;
	}

	@Column(name = "temperaturac", precision = 4)
	public BigDecimal getTemperaturac() {
		return this.temperaturac;
	}

	public void setTemperaturac(BigDecimal temperaturac) {
		this.temperaturac = temperaturac;
	}

	@Column(name = "presion")
	public Integer getPresion() {
		return this.presion;
	}

	public void setPresion(Integer presion) {
		this.presion = presion;
	}

	@Column(name = "fcia_resp")
	public Short getFciaResp() {
		return this.fciaResp;
	}

	public void setFciaResp(Short fciaResp) {
		this.fciaResp = fciaResp;
	}

	@Column(name = "fcia_card")
	public Short getFciaCard() {
		return this.fciaCard;
	}

	public void setFciaCard(Short fciaCard) {
		this.fciaCard = fciaCard;
	}

	@Column(name = "lugar_atencion", length = 8)
	public String getLugarAtencion() {
		return this.lugarAtencion;
	}

	public void setLugarAtencion(String lugarAtencion) {
		this.lugarAtencion = lugarAtencion;
	}

	@Column(name = "consulta", length = 16)
	public String getConsulta() {
		return this.consulta;
	}

	public void setConsulta(String consulta) {
		this.consulta = consulta;
	}

	@Column(name = "seg_chick", length = 1)
	public Character getSegChick() {
		return this.segChick;
	}

	public void setSegChick(Character segChick) {
		this.segChick = segChick;
	}

	@Column(name = "turno", length = 1)
	public Character getTurno() {
		return this.turno;
	}

	public void setTurno(Character turno) {
		this.turno = turno;
	}

	@Column(name = "tem_medc", precision = 4)
	public BigDecimal getTemMedc() {
		return this.temMedc;
	}

	public void setTemMedc(BigDecimal temMedc) {
		this.temMedc = temMedc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ult_dia_fiebre", length = 29)
	public Date getUltDiaFiebre() {
		return this.ultDiaFiebre;
	}

	public void setUltDiaFiebre(Date ultDiaFiebre) {
		this.ultDiaFiebre = ultDiaFiebre;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ult_dosis_antipiretico", length = 29)
	public Date getUltDosisAntipiretico() {
		return this.ultDosisAntipiretico;
	}

	public void setUltDosisAntipiretico(Date ultDosisAntipiretico) {
		this.ultDosisAntipiretico = ultDosisAntipiretico;
	}

	@Column(name = "fiebre", length = 1)
	public Character getFiebre() {
		return this.fiebre;
	}

	public void setFiebre(Character fiebre) {
		this.fiebre = fiebre;
	}

	@Column(name = "astenia", length = 1)
	public Character getAstenia() {
		return this.astenia;
	}

	public void setAstenia(Character astenia) {
		this.astenia = astenia;
	}

	@Column(name = "asomnoliento", length = 1)
	public Character getAsomnoliento() {
		return this.asomnoliento;
	}

	public void setAsomnoliento(Character asomnoliento) {
		this.asomnoliento = asomnoliento;
	}

	@Column(name = "mal_estado", length = 1)
	public Character getMalEstado() {
		return this.malEstado;
	}

	public void setMalEstado(Character malEstado) {
		this.malEstado = malEstado;
	}

	@Column(name = "perdida_consciencia", length = 1)
	public Character getPerdidaConsciencia() {
		return this.perdidaConsciencia;
	}

	public void setPerdidaConsciencia(Character perdidaConsciencia) {
		this.perdidaConsciencia = perdidaConsciencia;
	}

	@Column(name = "inquieto", length = 1)
	public Character getInquieto() {
		return this.inquieto;
	}

	public void setInquieto(Character inquieto) {
		this.inquieto = inquieto;
	}

	@Column(name = "convulsiones", length = 1)
	public Character getConvulsiones() {
		return this.convulsiones;
	}

	public void setConvulsiones(Character convulsiones) {
		this.convulsiones = convulsiones;
	}

	@Column(name = "hipotermia", length = 1)
	public Character getHipotermia() {
		return this.hipotermia;
	}

	public void setHipotermia(Character hipotermia) {
		this.hipotermia = hipotermia;
	}

	@Column(name = "letargia", length = 1)
	public Character getLetargia() {
		return this.letargia;
	}

	public void setLetargia(Character letargia) {
		this.letargia = letargia;
	}

	@Column(name = "cefalea", length = 1)
	public Character getCefalea() {
		return this.cefalea;
	}

	public void setCefalea(Character cefalea) {
		this.cefalea = cefalea;
	}

	@Column(name = "rigidez_cuello", length = 1)
	public Character getRigidezCuello() {
		return this.rigidezCuello;
	}

	public void setRigidezCuello(Character rigidezCuello) {
		this.rigidezCuello = rigidezCuello;
	}

	@Column(name = "inyeccion_conjuntival", length = 1)
	public Character getInyeccionConjuntival() {
		return this.inyeccionConjuntival;
	}

	public void setInyeccionConjuntival(Character inyeccionConjuntival) {
		this.inyeccionConjuntival = inyeccionConjuntival;
	}

	@Column(name = "hemorragia_suconjuntival", length = 1)
	public Character getHemorragiaSuconjuntival() {
		return this.hemorragiaSuconjuntival;
	}

	public void setHemorragiaSuconjuntival(Character hemorragiaSuconjuntival) {
		this.hemorragiaSuconjuntival = hemorragiaSuconjuntival;
	}

	@Column(name = "dolor_retroocular", length = 1)
	public Character getDolorRetroocular() {
		return this.dolorRetroocular;
	}

	public void setDolorRetroocular(Character dolorRetroocular) {
		this.dolorRetroocular = dolorRetroocular;
	}

	@Column(name = "fontanela_abombada", length = 1)
	public Character getFontanelaAbombada() {
		return this.fontanelaAbombada;
	}

	public void setFontanelaAbombada(Character fontanelaAbombada) {
		this.fontanelaAbombada = fontanelaAbombada;
	}

	@Column(name = "ictericia_conuntival", length = 1)
	public Character getIctericiaConuntival() {
		return this.ictericiaConuntival;
	}

	public void setIctericiaConuntival(Character ictericiaConuntival) {
		this.ictericiaConuntival = ictericiaConuntival;
	}

	@Column(name = "eritema", length = 1)
	public Character getEritema() {
		return this.eritema;
	}

	public void setEritema(Character eritema) {
		this.eritema = eritema;
	}

	@Column(name = "dolor_garganta", length = 1)
	public Character getDolorGarganta() {
		return this.dolorGarganta;
	}

	public void setDolorGarganta(Character dolorGarganta) {
		this.dolorGarganta = dolorGarganta;
	}

	@Column(name = "adenopatias_cervicales", length = 1)
	public Character getAdenopatiasCervicales() {
		return this.adenopatiasCervicales;
	}

	public void setAdenopatiasCervicales(Character adenopatiasCervicales) {
		this.adenopatiasCervicales = adenopatiasCervicales;
	}

	@Column(name = "exudado", length = 1)
	public Character getExudado() {
		return this.exudado;
	}

	public void setExudado(Character exudado) {
		this.exudado = exudado;
	}

	@Column(name = "petequias_mucosa", length = 1)
	public Character getPetequiasMucosa() {
		return this.petequiasMucosa;
	}

	public void setPetequiasMucosa(Character petequiasMucosa) {
		this.petequiasMucosa = petequiasMucosa;
	}

	@Column(name = "tos", length = 1)
	public Character getTos() {
		return this.tos;
	}

	public void setTos(Character tos) {
		this.tos = tos;
	}

	@Column(name = "rinorrea", length = 1)
	public Character getRinorrea() {
		return this.rinorrea;
	}

	public void setRinorrea(Character rinorrea) {
		this.rinorrea = rinorrea;
	}

	@Column(name = "congestion_nasal", length = 1)
	public Character getCongestionNasal() {
		return this.congestionNasal;
	}

	public void setCongestionNasal(Character congestionNasal) {
		this.congestionNasal = congestionNasal;
	}

	@Column(name = "otalgia", length = 1)
	public Character getOtalgia() {
		return this.otalgia;
	}

	public void setOtalgia(Character otalgia) {
		this.otalgia = otalgia;
	}

	@Column(name = "aleteo_nasal", length = 1)
	public Character getAleteoNasal() {
		return this.aleteoNasal;
	}

	public void setAleteoNasal(Character aleteoNasal) {
		this.aleteoNasal = aleteoNasal;
	}

	@Column(name = "apnea", length = 1)
	public Character getApnea() {
		return this.apnea;
	}

	public void setApnea(Character apnea) {
		this.apnea = apnea;
	}

	@Column(name = "respiracion_rapida", length = 1)
	public Character getRespiracionRapida() {
		return this.respiracionRapida;
	}

	public void setRespiracionRapida(Character respiracionRapida) {
		this.respiracionRapida = respiracionRapida;
	}

	@Column(name = "quejido_espiratorio", length = 1)
	public Character getQuejidoEspiratorio() {
		return this.quejidoEspiratorio;
	}

	public void setQuejidoEspiratorio(Character quejidoEspiratorio) {
		this.quejidoEspiratorio = quejidoEspiratorio;
	}

	@Column(name = "estirador_reposo", length = 1)
	public Character getEstiradorReposo() {
		return this.estiradorReposo;
	}

	public void setEstiradorReposo(Character estiradorReposo) {
		this.estiradorReposo = estiradorReposo;
	}

	@Column(name = "tiraje_subcostal", length = 1)
	public Character getTirajeSubcostal() {
		return this.tirajeSubcostal;
	}

	public void setTirajeSubcostal(Character tirajeSubcostal) {
		this.tirajeSubcostal = tirajeSubcostal;
	}

	@Column(name = "sibilancias", length = 1)
	public Character getSibilancias() {
		return this.sibilancias;
	}

	public void setSibilancias(Character sibilancias) {
		this.sibilancias = sibilancias;
	}

	@Column(name = "crepitos", length = 1)
	public Character getCrepitos() {
		return this.crepitos;
	}

	public void setCrepitos(Character crepitos) {
		this.crepitos = crepitos;
	}

	@Column(name = "roncos", length = 1)
	public Character getRoncos() {
		return this.roncos;
	}

	public void setRoncos(Character roncos) {
		this.roncos = roncos;
	}

	@Column(name = "otra_fif", length = 1)
	public Character getOtraFif() {
		return this.otraFif;
	}

	public void setOtraFif(Character otraFif) {
		this.otraFif = otraFif;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "nueva_fif", length = 13)
	public Date getNuevaFif() {
		return this.nuevaFif;
	}

	public void setNuevaFif(Date nuevaFif) {
		this.nuevaFif = nuevaFif;
	}

	@Column(name = "poco_apetito", length = 1)
	public Character getPocoApetito() {
		return this.pocoApetito;
	}

	public void setPocoApetito(Character pocoApetito) {
		this.pocoApetito = pocoApetito;
	}

	@Column(name = "nausea", length = 1)
	public Character getNausea() {
		return this.nausea;
	}

	public void setNausea(Character nausea) {
		this.nausea = nausea;
	}

	@Column(name = "dificultad_alimentarse", length = 1)
	public Character getDificultadAlimentarse() {
		return this.dificultadAlimentarse;
	}

	public void setDificultadAlimentarse(Character dificultadAlimentarse) {
		this.dificultadAlimentarse = dificultadAlimentarse;
	}

	@Column(name = "vomito_12horas", length = 1)
	public Character getVomito12horas() {
		return this.vomito12horas;
	}

	public void setVomito12horas(Character vomito12horas) {
		this.vomito12horas = vomito12horas;
	}

	@Column(name = "diarrea", length = 1)
	public Character getDiarrea() {
		return this.diarrea;
	}

	public void setDiarrea(Character diarrea) {
		this.diarrea = diarrea;
	}

	@Column(name = "diarrea_sangre", length = 1)
	public Character getDiarreaSangre() {
		return this.diarreaSangre;
	}

	public void setDiarreaSangre(Character diarreaSangre) {
		this.diarreaSangre = diarreaSangre;
	}

	@Column(name = "estrenimiento", length = 1)
	public Character getEstrenimiento() {
		return this.estrenimiento;
	}

	public void setEstrenimiento(Character estrenimiento) {
		this.estrenimiento = estrenimiento;
	}

	@Column(name = "dolor_ab_intermitente", length = 1)
	public Character getDolorAbIntermitente() {
		return this.dolorAbIntermitente;
	}

	public void setDolorAbIntermitente(Character dolorAbIntermitente) {
		this.dolorAbIntermitente = dolorAbIntermitente;
	}

	@Column(name = "dolor_ab_continuo", length = 1)
	public Character getDolorAbContinuo() {
		return this.dolorAbContinuo;
	}

	public void setDolorAbContinuo(Character dolorAbContinuo) {
		this.dolorAbContinuo = dolorAbContinuo;
	}

	@Column(name = "epigastralgia", length = 1)
	public Character getEpigastralgia() {
		return this.epigastralgia;
	}

	public void setEpigastralgia(Character epigastralgia) {
		this.epigastralgia = epigastralgia;
	}

	@Column(name = "intolerancia_oral", length = 1)
	public Character getIntoleranciaOral() {
		return this.intoleranciaOral;
	}

	public void setIntoleranciaOral(Character intoleranciaOral) {
		this.intoleranciaOral = intoleranciaOral;
	}

	@Column(name = "distension_abdominal", length = 1)
	public Character getDistensionAbdominal() {
		return this.distensionAbdominal;
	}

	public void setDistensionAbdominal(Character distensionAbdominal) {
		this.distensionAbdominal = distensionAbdominal;
	}

	@Column(name = "hepatomegalia", length = 1)
	public Character getHepatomegalia() {
		return this.hepatomegalia;
	}

	public void setHepatomegalia(Character hepatomegalia) {
		this.hepatomegalia = hepatomegalia;
	}

	@Column(name = "lengua_mucosas_secas", length = 1)
	public Character getLenguaMucosasSecas() {
		return this.lenguaMucosasSecas;
	}

	public void setLenguaMucosasSecas(Character lenguaMucosasSecas) {
		this.lenguaMucosasSecas = lenguaMucosasSecas;
	}

	@Column(name = "pliegue_cutaneo", length = 1)
	public Character getPliegueCutaneo() {
		return this.pliegueCutaneo;
	}

	public void setPliegueCutaneo(Character pliegueCutaneo) {
		this.pliegueCutaneo = pliegueCutaneo;
	}

	@Column(name = "orina_reducida", length = 1)
	public Character getOrinaReducida() {
		return this.orinaReducida;
	}

	public void setOrinaReducida(Character orinaReducida) {
		this.orinaReducida = orinaReducida;
	}

	@Column(name = "bebe_con_sed", length = 1)
	public Character getBebeConSed() {
		return this.bebeConSed;
	}

	public void setBebeConSed(Character bebeConSed) {
		this.bebeConSed = bebeConSed;
	}

	@Column(name = "ojos_hundidos", length = 10)
	public String getOjosHundidos() {
		return this.ojosHundidos;
	}

	public void setOjosHundidos(String ojosHundidos) {
		this.ojosHundidos = ojosHundidos;
	}

	@Column(name = "fontanela_hundida", length = 1)
	public Character getFontanelaHundida() {
		return this.fontanelaHundida;
	}

	public void setFontanelaHundida(Character fontanelaHundida) {
		this.fontanelaHundida = fontanelaHundida;
	}

	@Column(name = "sintomas_urinarios", length = 1)
	public Character getSintomasUrinarios() {
		return this.sintomasUrinarios;
	}

	public void setSintomasUrinarios(Character sintomasUrinarios) {
		this.sintomasUrinarios = sintomasUrinarios;
	}

	@Column(name = "leucocituria", length = 1)
	public Character getLeucocituria() {
		return this.leucocituria;
	}

	public void setLeucocituria(Character leucocituria) {
		this.leucocituria = leucocituria;
	}

	@Column(name = "nitritos", length = 1)
	public Character getNitritos() {
		return this.nitritos;
	}

	public void setNitritos(Character nitritos) {
		this.nitritos = nitritos;
	}

	@Column(name = "bilirrubinuria", length = 1)
	public Character getBilirrubinuria() {
		return this.bilirrubinuria;
	}

	public void setBilirrubinuria(Character bilirrubinuria) {
		this.bilirrubinuria = bilirrubinuria;
	}

	@Column(name = "altralgia", length = 1)
	public Character getAltralgia() {
		return this.altralgia;
	}

	public void setAltralgia(Character altralgia) {
		this.altralgia = altralgia;
	}

	@Column(name = "mialgia", length = 1)
	public Character getMialgia() {
		return this.mialgia;
	}

	public void setMialgia(Character mialgia) {
		this.mialgia = mialgia;
	}

	@Column(name = "lumbalgia", length = 1)
	public Character getLumbalgia() {
		return this.lumbalgia;
	}

	public void setLumbalgia(Character lumbalgia) {
		this.lumbalgia = lumbalgia;
	}

	@Column(name = "dolor_cuello", length = 1)
	public Character getDolorCuello() {
		return this.dolorCuello;
	}

	public void setDolorCuello(Character dolorCuello) {
		this.dolorCuello = dolorCuello;
	}

	@Column(name = "tenosinovitis", length = 1)
	public Character getTenosinovitis() {
		return this.tenosinovitis;
	}

	public void setTenosinovitis(Character tenosinovitis) {
		this.tenosinovitis = tenosinovitis;
	}

	@Column(name = "artralgia_proximal", length = 1)
	public Character getArtralgiaProximal() {
		return this.artralgiaProximal;
	}

	public void setArtralgiaProximal(Character artralgiaProximal) {
		this.artralgiaProximal = artralgiaProximal;
	}

	@Column(name = "artralgia_distal", length = 1)
	public Character getArtralgiaDistal() {
		return this.artralgiaDistal;
	}

	public void setArtralgiaDistal(Character artralgiaDistal) {
		this.artralgiaDistal = artralgiaDistal;
	}

	@Column(name = "conjuntivitis", length = 1)
	public Character getConjuntivitis() {
		return this.conjuntivitis;
	}

	public void setConjuntivitis(Character conjuntivitis) {
		this.conjuntivitis = conjuntivitis;
	}

	@Column(name = "edema_munecas", length = 1)
	public Character getEdemaMunecas() {
		return this.edemaMunecas;
	}

	public void setEdemaMunecas(Character edemaMunecas) {
		this.edemaMunecas = edemaMunecas;
	}

	@Column(name = "edema_codos", length = 1)
	public Character getEdemaCodos() {
		return this.edemaCodos;
	}

	public void setEdemaCodos(Character edemaCodos) {
		this.edemaCodos = edemaCodos;
	}

	@Column(name = "edema_hombros", length = 1)
	public Character getEdemaHombros() {
		return this.edemaHombros;
	}

	public void setEdemaHombros(Character edemaHombros) {
		this.edemaHombros = edemaHombros;
	}

	@Column(name = "edema_rodillas", length = 1)
	public Character getEdemaRodillas() {
		return this.edemaRodillas;
	}

	public void setEdemaRodillas(Character edemaRodillas) {
		this.edemaRodillas = edemaRodillas;
	}

	@Column(name = "edema_tobillos", length = 1)
	public Character getEdemaTobillos() {
		return this.edemaTobillos;
	}

	public void setEdemaTobillos(Character edemaTobillos) {
		this.edemaTobillos = edemaTobillos;
	}

	@Column(name = "rahs_localizado", length = 1)
	public Character getRahsLocalizado() {
		return this.rahsLocalizado;
	}

	public void setRahsLocalizado(Character rahsLocalizado) {
		this.rahsLocalizado = rahsLocalizado;
	}

	@Column(name = "rahs_generalizado", length = 1)
	public Character getRahsGeneralizado() {
		return this.rahsGeneralizado;
	}

	public void setRahsGeneralizado(Character rahsGeneralizado) {
		this.rahsGeneralizado = rahsGeneralizado;
	}

	@Column(name = "rash_eritematoso", length = 1)
	public Character getRashEritematoso() {
		return this.rashEritematoso;
	}

	public void setRashEritematoso(Character rashEritematoso) {
		this.rashEritematoso = rashEritematoso;
	}

	@Column(name = "rahs_macular", length = 1)
	public Character getRahsMacular() {
		return this.rahsMacular;
	}

	public void setRahsMacular(Character rahsMacular) {
		this.rahsMacular = rahsMacular;
	}

	@Column(name = "rash_papular", length = 1)
	public Character getRashPapular() {
		return this.rashPapular;
	}

	public void setRashPapular(Character rashPapular) {
		this.rashPapular = rashPapular;
	}

	@Column(name = "rahs_moteada", length = 1)
	public Character getRahsMoteada() {
		return this.rahsMoteada;
	}

	public void setRahsMoteada(Character rahsMoteada) {
		this.rahsMoteada = rahsMoteada;
	}

	@Column(name = "rubor_facial", length = 1)
	public Character getRuborFacial() {
		return this.ruborFacial;
	}

	public void setRuborFacial(Character ruborFacial) {
		this.ruborFacial = ruborFacial;
	}

	@Column(name = "equimosis", length = 1)
	public Character getEquimosis() {
		return this.equimosis;
	}

	public void setEquimosis(Character equimosis) {
		this.equimosis = equimosis;
	}

	@Column(name = "cianosis_central", length = 1)
	public Character getCianosisCentral() {
		return this.cianosisCentral;
	}

	public void setCianosisCentral(Character cianosisCentral) {
		this.cianosisCentral = cianosisCentral;
	}

	@Column(name = "ictericia", length = 1)
	public Character getIctericia() {
		return this.ictericia;
	}

	public void setIctericia(Character ictericia) {
		this.ictericia = ictericia;
	}

	@Column(name = "obeso", length = 1)
	public Character getObeso() {
		return this.obeso;
	}

	public void setObeso(Character obeso) {
		this.obeso = obeso;
	}

	@Column(name = "sobrepeso", length = 1)
	public Character getSobrepeso() {
		return this.sobrepeso;
	}

	public void setSobrepeso(Character sobrepeso) {
		this.sobrepeso = sobrepeso;
	}

	@Column(name = "sospecha_problema", length = 1)
	public Character getSospechaProblema() {
		return this.sospechaProblema;
	}

	public void setSospechaProblema(Character sospechaProblema) {
		this.sospechaProblema = sospechaProblema;
	}

	@Column(name = "normal", length = 1)
	public Character getNormal() {
		return this.normal;
	}

	public void setNormal(Character normal) {
		this.normal = normal;
	}

	@Column(name = "bajo_peso", length = 1)
	public Character getBajoPeso() {
		return this.bajoPeso;
	}

	public void setBajoPeso(Character bajoPeso) {
		this.bajoPeso = bajoPeso;
	}

	@Column(name = "bajo_peso_severo", length = 1)
	public Character getBajoPesoSevero() {
		return this.bajoPesoSevero;
	}

	public void setBajoPesoSevero(Character bajoPesoSevero) {
		this.bajoPesoSevero = bajoPesoSevero;
	}

	@Column(name = "lactancia_materna", length = 1)
	public Character getLactanciaMaterna() {
		return this.lactanciaMaterna;
	}

	public void setLactanciaMaterna(Character lactanciaMaterna) {
		this.lactanciaMaterna = lactanciaMaterna;
	}

	@Column(name = "vacunas_completas", length = 1)
	public Character getVacunasCompletas() {
		return this.vacunasCompletas;
	}

	public void setVacunasCompletas(Character vacunasCompletas) {
		this.vacunasCompletas = vacunasCompletas;
	}

	@Column(name = "vacuna_influenza", length = 1)
	public Character getVacunaInfluenza() {
		return this.vacunaInfluenza;
	}

	public void setVacunaInfluenza(Character vacunaInfluenza) {
		this.vacunaInfluenza = vacunaInfluenza;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_vacuna", length = 13)
	public Date getFechaVacuna() {
		return this.fechaVacuna;
	}

	public void setFechaVacuna(Date fechaVacuna) {
		this.fechaVacuna = fechaVacuna;
	}

	@Column(name = "interconsulta_pediatrica", length = 1)
	public Character getInterconsultaPediatrica() {
		return this.interconsultaPediatrica;
	}

	public void setInterconsultaPediatrica(Character interconsultaPediatrica) {
		this.interconsultaPediatrica = interconsultaPediatrica;
	}

	@Column(name = "referencia_hospital", length = 1)
	public Character getReferenciaHospital() {
		return this.referenciaHospital;
	}

	public void setReferenciaHospital(Character referenciaHospital) {
		this.referenciaHospital = referenciaHospital;
	}

	@Column(name = "referencia_dengue", length = 1)
	public Character getReferenciaDengue() {
		return this.referenciaDengue;
	}

	public void setReferenciaDengue(Character referenciaDengue) {
		this.referenciaDengue = referenciaDengue;
	}

	@Column(name = "referencia_irag", length = 1)
	public Character getReferenciaIrag() {
		return this.referenciaIrag;
	}

	public void setReferenciaIrag(Character referenciaIrag) {
		this.referenciaIrag = referenciaIrag;
	}

	@Column(name = "referencia_chik", length = 1)
	public Character getReferenciaChik() {
		return this.referenciaChik;
	}

	public void setReferenciaChik(Character referenciaChik) {
		this.referenciaChik = referenciaChik;
	}

	@Column(name = "eti", length = 1)
	public Character getEti() {
		return this.eti;
	}

	public void setEti(Character eti) {
		this.eti = eti;
	}

	@Column(name = "irag", length = 1)
	public Character getIrag() {
		return this.irag;
	}

	public void setIrag(Character irag) {
		this.irag = irag;
	}

	@Column(name = "neumonia", length = 1)
	public Character getNeumonia() {
		return this.neumonia;
	}

	public void setNeumonia(Character neumonia) {
		this.neumonia = neumonia;
	}

	@Column(name = "saturaciono2")
	public Short getSaturaciono2() {
		return this.saturaciono2;
	}

	public void setSaturaciono2(Short saturaciono2) {
		this.saturaciono2 = saturaciono2;
	}

	@Column(name = "imc", precision = 5)
	public BigDecimal getImc() {
		return this.imc;
	}

	public void setImc(BigDecimal imc) {
		this.imc = imc;
	}

	@Column(name = "categoria", length = 2)
	public String getCategoria() {
		return this.categoria;
	}

	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}

	@Column(name = "cambio_categoria", length = 1)
	public Character getCambioCategoria() {
		return this.cambioCategoria;
	}

	public void setCambioCategoria(Character cambioCategoria) {
		this.cambioCategoria = cambioCategoria;
	}

	@Column(name = "manifestacion_hemorragica", length = 1)
	public Character getManifestacionHemorragica() {
		return this.manifestacionHemorragica;
	}

	public void setManifestacionHemorragica(Character manifestacionHemorragica) {
		this.manifestacionHemorragica = manifestacionHemorragica;
	}

	@Column(name = "prueba_torniquete_positiva", length = 1)
	public Character getPruebaTorniquetePositiva() {
		return this.pruebaTorniquetePositiva;
	}

	public void setPruebaTorniquetePositiva(Character pruebaTorniquetePositiva) {
		this.pruebaTorniquetePositiva = pruebaTorniquetePositiva;
	}

	@Column(name = "petequia_10_pt", length = 1)
	public Character getPetequia10Pt() {
		return this.petequia10Pt;
	}

	public void setPetequia10Pt(Character petequia10Pt) {
		this.petequia10Pt = petequia10Pt;
	}

	@Column(name = "petequia_20_pt", length = 1)
	public Character getPetequia20Pt() {
		return this.petequia20Pt;
	}

	public void setPetequia20Pt(Character petequia20Pt) {
		this.petequia20Pt = petequia20Pt;
	}

	@Column(name = "piel_extremidades_frias", length = 1)
	public Character getPielExtremidadesFrias() {
		return this.pielExtremidadesFrias;
	}

	public void setPielExtremidadesFrias(Character pielExtremidadesFrias) {
		this.pielExtremidadesFrias = pielExtremidadesFrias;
	}

	@Column(name = "palidez_en_extremidades", length = 1)
	public Character getPalidezEnExtremidades() {
		return this.palidezEnExtremidades;
	}

	public void setPalidezEnExtremidades(Character palidezEnExtremidades) {
		this.palidezEnExtremidades = palidezEnExtremidades;
	}

	@Column(name = "epistaxis", length = 1)
	public Character getEpistaxis() {
		return this.epistaxis;
	}

	public void setEpistaxis(Character epistaxis) {
		this.epistaxis = epistaxis;
	}

	@Column(name = "gingivorragia", length = 1)
	public Character getGingivorragia() {
		return this.gingivorragia;
	}

	public void setGingivorragia(Character gingivorragia) {
		this.gingivorragia = gingivorragia;
	}

	@Column(name = "petequias_espontaneas", length = 1)
	public Character getPetequiasEspontaneas() {
		return this.petequiasEspontaneas;
	}

	public void setPetequiasEspontaneas(Character petequiasEspontaneas) {
		this.petequiasEspontaneas = petequiasEspontaneas;
	}

	@Column(name = "llenado_capilar_2seg", length = 1)
	public Character getLlenadoCapilar2seg() {
		return this.llenadoCapilar2seg;
	}

	public void setLlenadoCapilar2seg(Character llenadoCapilar2seg) {
		this.llenadoCapilar2seg = llenadoCapilar2seg;
	}

	@Column(name = "cianosis", length = 1)
	public Character getCianosis() {
		return this.cianosis;
	}

	public void setCianosis(Character cianosis) {
		this.cianosis = cianosis;
	}

	@Column(name = "linfocitosa_atipicos", precision = 5)
	public BigDecimal getLinfocitosaAtipicos() {
		return this.linfocitosaAtipicos;
	}

	public void setLinfocitosaAtipicos(BigDecimal linfocitosaAtipicos) {
		this.linfocitosaAtipicos = linfocitosaAtipicos;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_linfocitos", length = 13)
	public Date getFechaLinfocitos() {
		return this.fechaLinfocitos;
	}

	public void setFechaLinfocitos(Date fechaLinfocitos) {
		this.fechaLinfocitos = fechaLinfocitos;
	}

	@Column(name = "hipermenorrea", length = 1)
	public Character getHipermenorrea() {
		return this.hipermenorrea;
	}

	public void setHipermenorrea(Character hipermenorrea) {
		this.hipermenorrea = hipermenorrea;
	}

	@Column(name = "hematemesis", length = 1)
	public Character getHematemesis() {
		return this.hematemesis;
	}

	public void setHematemesis(Character hematemesis) {
		this.hematemesis = hematemesis;
	}

	@Column(name = "melena", length = 1)
	public Character getMelena() {
		return this.melena;
	}

	public void setMelena(Character melena) {
		this.melena = melena;
	}

	@Column(name = "hemoconcentracion")
	public Short getHemoconcentracion() {
		return this.hemoconcentracion;
	}

	public void setHemoconcentracion(Short hemoconcentracion) {
		this.hemoconcentracion = hemoconcentracion;
	}

	@Column(name = "hospitalizado", length = 1)
	public Character getHospitalizado() {
		return this.hospitalizado;
	}

	public void setHospitalizado(Character hospitalizado) {
		this.hospitalizado = hospitalizado;
	}

	@Column(name = "hospitalizado_especificar", length = 500) // 500
	public String getHospitalizadoEspecificar() {
		return this.hospitalizadoEspecificar;
	}

	public void setHospitalizadoEspecificar(String hospitalizadoEspecificar) {
		this.hospitalizadoEspecificar = hospitalizadoEspecificar;
	}

	@Column(name = "transfusion_sangre", length = 1)
	public Character getTransfusionSangre() {
		return this.transfusionSangre;
	}

	public void setTransfusionSangre(Character transfusionSangre) {
		this.transfusionSangre = transfusionSangre;
	}

	@Column(name = "transfusion_especificar", length = 500) //500
	public String getTransfusionEspecificar() {
		return this.transfusionEspecificar;
	}

	public void setTransfusionEspecificar(String transfusionEspecificar) {
		this.transfusionEspecificar = transfusionEspecificar;
	}

	@Column(name = "tomando_medicamento", length = 1)
	public Character getTomandoMedicamento() {
		return this.tomandoMedicamento;
	}

	public void setTomandoMedicamento(Character tomandoMedicamento) {
		this.tomandoMedicamento = tomandoMedicamento;
	}

	@Column(name = "medicamento_especificar", length = 500) //500
	public String getMedicamentoEspecificar() {
		return this.medicamentoEspecificar;
	}

	public void setMedicamentoEspecificar(String medicamentoEspecificar) {
		this.medicamentoEspecificar = medicamentoEspecificar;
	}

	@Column(name = "medicamento_distinto", length = 1)
	public Character getMedicamentoDistinto() {
		return this.medicamentoDistinto;
	}

	public void setMedicamentoDistinto(Character medicamentoDistinto) {
		this.medicamentoDistinto = medicamentoDistinto;
	}

	@Column(name = "medicamento_dist_especificar", length = 500) //500
	public String getMedicamentoDistEspecificar() {
		return this.medicamentoDistEspecificar;
	}

	public void setMedicamentoDistEspecificar(String medicamentoDistEspecificar) {
		this.medicamentoDistEspecificar = medicamentoDistEspecificar;
	}

	@Column(name = "bhc", length = 1)
	public Character getBhc() {
		return this.bhc;
	}

	public void setBhc(Character bhc) {
		this.bhc = bhc;
	}

	@Column(name = "serologia_dengue", length = 1)
	public Character getSerologiaDengue() {
		return this.serologiaDengue;
	}

	public void setSerologiaDengue(Character serologiaDengue) {
		this.serologiaDengue = serologiaDengue;
	}

	@Column(name = "serologia_chik", length = 1)
	public Character getSerologiaChik() {
		return this.serologiaChik;
	}

	public void setSerologiaChik(Character serologiaChik) {
		this.serologiaChik = serologiaChik;
	}

	@Column(name = "gota_gruesa", length = 1)
	public Character getGotaGruesa() {
		return this.gotaGruesa;
	}

	public void setGotaGruesa(Character gotaGruesa) {
		this.gotaGruesa = gotaGruesa;
	}

	@Column(name = "extendido_periferico", length = 1)
	public Character getExtendidoPeriferico() {
		return this.extendidoPeriferico;
	}

	public void setExtendidoPeriferico(Character extendidoPeriferico) {
		this.extendidoPeriferico = extendidoPeriferico;
	}

	@Column(name = "ego", length = 1)
	public Character getEgo() {
		return this.ego;
	}

	public void setEgo(Character ego) {
		this.ego = ego;
	}

	@Column(name = "egh", length = 1)
	public Character getEgh() {
		return this.egh;
	}

	public void setEgh(Character egh) {
		this.egh = egh;
	}

	@Column(name = "citologia_fecal", length = 1)
	public Character getCitologiaFecal() {
		return this.citologiaFecal;
	}

	public void setCitologiaFecal(Character citologiaFecal) {
		this.citologiaFecal = citologiaFecal;
	}

	@Column(name = "factor_reumatoideo", length = 1)
	public Character getFactorReumatoideo() {
		return this.factorReumatoideo;
	}

	public void setFactorReumatoideo(Character factorReumatoideo) {
		this.factorReumatoideo = factorReumatoideo;
	}

	@Column(name = "albumina", length = 1)
	public Character getAlbumina() {
		return this.albumina;
	}

	public void setAlbumina(Character albumina) {
		this.albumina = albumina;
	}

	@Column(name = "ast_alt", length = 1)
	public Character getAstAlt() {
		return this.astAlt;
	}

	public void setAstAlt(Character astAlt) {
		this.astAlt = astAlt;
	}

	@Column(name = "bilirrubinas", length = 1)
	public Character getBilirrubinas() {
		return this.bilirrubinas;
	}

	public void setBilirrubinas(Character bilirrubinas) {
		this.bilirrubinas = bilirrubinas;
	}

	@Column(name = "cpk", length = 1)
	public Character getCpk() {
		return this.cpk;
	}

	public void setCpk(Character cpk) {
		this.cpk = cpk;
	}

	@Column(name = "colesterol", length = 1)
	public Character getColesterol() {
		return this.colesterol;
	}

	public void setColesterol(Character colesterol) {
		this.colesterol = colesterol;
	}

	@Column(name = "influenza", length = 1)
	public Character getInfluenza() {
		return this.influenza;
	}

	public void setInfluenza(Character influenza) {
		this.influenza = influenza;
	}

	@Column(name = "otro_examen_lab", length = 32)
	public String getOtroExamenLab() {
		return this.otroExamenLab;
	}

	public void setOtroExamenLab(String otroExamenLab) {
		this.otroExamenLab = otroExamenLab;
	}
	
	@Column(name = "oel", length = 1)
	public Character getOel() {
		return oel;
	}

	public void setOel(Character oel) {
		this.oel = oel;
	}

	@Column(name = "num_orden_laboratorio")
	public Integer getNumOrdenLaboratorio() {
		return this.numOrdenLaboratorio;
	}

	public void setNumOrdenLaboratorio(Integer numOrdenLaboratorio) {
		this.numOrdenLaboratorio = numOrdenLaboratorio;
	}

	@Column(name = "acetaminofen", length = 1)
	public Character getAcetaminofen() {
		return this.acetaminofen;
	}

	public void setAcetaminofen(Character acetaminofen) {
		this.acetaminofen = acetaminofen;
	}

	@Column(name = "asa", length = 1)
	public Character getAsa() {
		return this.asa;
	}

	public void setAsa(Character asa) {
		this.asa = asa;
	}

	@Column(name = "ibuprofen", length = 1)
	public Character getIbuprofen() {
		return this.ibuprofen;
	}

	public void setIbuprofen(Character ibuprofen) {
		this.ibuprofen = ibuprofen;
	}

	@Column(name = "penicilina", length = 1)
	public Character getPenicilina() {
		return this.penicilina;
	}

	public void setPenicilina(Character penicilina) {
		this.penicilina = penicilina;
	}

	@Column(name = "amoxicilina", length = 1)
	public Character getAmoxicilina() {
		return this.amoxicilina;
	}

	public void setAmoxicilina(Character amoxicilina) {
		this.amoxicilina = amoxicilina;
	}

	@Column(name = "dicloxacilina", length = 1)
	public Character getDicloxacilina() {
		return this.dicloxacilina;
	}

	public void setDicloxacilina(Character dicloxacilina) {
		this.dicloxacilina = dicloxacilina;
	}

	@Column(name = "otro_antibiotico", length = 32)
	public String getOtroAntibiotico() {
		return this.otroAntibiotico;
	}

	public void setOtroAntibiotico(String otroAntibiotico) {
		this.otroAntibiotico = otroAntibiotico;
	}

	@Column(name = "furazolidona", length = 1)
	public Character getFurazolidona() {
		return this.furazolidona;
	}

	public void setFurazolidona(Character furazolidona) {
		this.furazolidona = furazolidona;
	}

	@Column(name = "metronidazol_tinidazol", length = 1)
	public Character getMetronidazolTinidazol() {
		return this.metronidazolTinidazol;
	}

	public void setMetronidazolTinidazol(Character metronidazolTinidazol) {
		this.metronidazolTinidazol = metronidazolTinidazol;
	}

	@Column(name = "albendazol_mebendazol", length = 1)
	public Character getAlbendazolMebendazol() {
		return this.albendazolMebendazol;
	}

	public void setAlbendazolMebendazol(Character albendazolMebendazol) {
		this.albendazolMebendazol = albendazolMebendazol;
	}

	@Column(name = "sulfato_ferroso", length = 1)
	public Character getSulfatoFerroso() {
		return this.sulfatoFerroso;
	}

	public void setSulfatoFerroso(Character sulfatoFerroso) {
		this.sulfatoFerroso = sulfatoFerroso;
	}

	@Column(name = "suero_oral", length = 1)
	public Character getSueroOral() {
		return this.sueroOral;
	}

	public void setSueroOral(Character sueroOral) {
		this.sueroOral = sueroOral;
	}

	@Column(name = "sulfato_zinc", length = 1)
	public Character getSulfatoZinc() {
		return this.sulfatoZinc;
	}

	public void setSulfatoZinc(Character sulfatoZinc) {
		this.sulfatoZinc = sulfatoZinc;
	}

	@Column(name = "liquidos_iv", length = 1)
	public Character getLiquidosIv() {
		return this.liquidosIv;
	}

	public void setLiquidosIv(Character liquidosIv) {
		this.liquidosIv = liquidosIv;
	}

	@Column(name = "prednisona", length = 1)
	public Character getPrednisona() {
		return this.prednisona;
	}

	public void setPrednisona(Character prednisona) {
		this.prednisona = prednisona;
	}

	@Column(name = "hidrocortisona_iv", length = 1)
	public Character getHidrocortisonaIv() {
		return this.hidrocortisonaIv;
	}

	public void setHidrocortisonaIv(Character hidrocortisonaIv) {
		this.hidrocortisonaIv = hidrocortisonaIv;
	}

	@Column(name = "salbutamol", length = 1)
	public Character getSalbutamol() {
		return this.salbutamol;
	}

	public void setSalbutamol(Character salbutamol) {
		this.salbutamol = salbutamol;
	}

	@Column(name = "oseltamivir", length = 1)
	public Character getOseltamivir() {
		return this.oseltamivir;
	}

	public void setOseltamivir(Character oseltamivir) {
		this.oseltamivir = oseltamivir;
	}

	@Column(name = "historia_examen_fisico")
	public String getHistoriaExamenFisico() {
		return this.historiaExamenFisico;
	}

	public void setHistoriaExamenFisico(String historiaExamenFisico) {
		this.historiaExamenFisico = historiaExamenFisico;
	}

	@Column(name = "diagnostico1")
	public Short getDiagnostico1() {
		return this.diagnostico1;
	}

	public void setDiagnostico1(Short diagnostico1) {
		this.diagnostico1 = diagnostico1;
	}

	@Column(name = "diagnostico2")
	public Short getDiagnostico2() {
		return this.diagnostico2;
	}

	public void setDiagnostico2(Short diagnostico2) {
		this.diagnostico2 = diagnostico2;
	}

	@Column(name = "diagnostico3")
	public Short getDiagnostico3() {
		return this.diagnostico3;
	}

	public void setDiagnostico3(Short diagnostico3) {
		this.diagnostico3 = diagnostico3;
	}

	@Column(name = "diagnostico4")
	public Short getDiagnostico4() {
		return this.diagnostico4;
	}

	public void setDiagnostico4(Short diagnostico4) {
		this.diagnostico4 = diagnostico4;
	}

	@Column(name = "otro_diagnostico", length = 500)
	public String getOtroDiagnostico() {
		return this.otroDiagnostico;
	}

	public void setOtroDiagnostico(String otroDiagnostico) {
		this.otroDiagnostico = otroDiagnostico;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "proxima_cita", length = 13)
	public Date getProximaCita() {
		return this.proximaCita;
	}

	public void setProximaCita(Date proximaCita) {
		this.proximaCita = proximaCita;
	}

	@Column(name = "horario_clases", length = 2)
	public String getHorarioClases() {
		return this.horarioClases;
	}

	public void setHorarioClases(String horarioClases) {
		this.horarioClases = horarioClases;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_cierre", length = 29)
	public Date getFechaCierre() {
		return this.fechaCierre;
	}

	public void setFechaCierre(Date fechaCierre) {
		this.fechaCierre = fechaCierre;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_cambio_turno", length = 29)
	public Date getFechaCambioTurno() {
		return this.fechaCambioTurno;
	}

	public void setFechaCambioTurno(Date fechaCambioTurno) {
		this.fechaCambioTurno = fechaCambioTurno;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_cierre_cambio_turno", length = 29)
	public Date getFechaCierreCambioTurno() {
		return this.fechaCierreCambioTurno;
	}

	public void setFechaCierreCambioTurno(Date fechaCierreCambioTurno) {
		this.fechaCierreCambioTurno = fechaCierreCambioTurno;
	}

	@Column(name = "am_pm_ult_dia_fiebre", length = 2)
	public String getAmPmUltDiaFiebre() {
		return this.amPmUltDiaFiebre;
	}

	public void setAmPmUltDiaFiebre(String amPmUltDiaFiebre) {
		this.amPmUltDiaFiebre = amPmUltDiaFiebre;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_ult_dosis_antipiretico", length = 15)
	public Date getHoraUltDosisAntipiretico() {
		return this.horaUltDosisAntipiretico;
	}

	public void setHoraUltDosisAntipiretico(Date horaUltDosisAntipiretico) {
		this.horaUltDosisAntipiretico = horaUltDosisAntipiretico;
	}

	@Column(name = "am_pm_ult_dosis_antipiretico", length = 6)
	public String getAmPmUltDosisAntipiretico() {
		return this.amPmUltDosisAntipiretico;
	}

	public void setAmPmUltDosisAntipiretico(String amPmUltDosisAntipiretico) {
		this.amPmUltDosisAntipiretico = amPmUltDosisAntipiretico;
	}

	@Column(name = "expediente_fisico", length = 16)
	public String getExpedienteFisico() {
		return this.expedienteFisico;
	}

	public void setExpedienteFisico(String expedienteFisico) {
		this.expedienteFisico = expedienteFisico;
	}

	@Column(name = "colegio", length = 3)
	public String getColegio() {
		return this.colegio;
	}

	public void setColegio(String colegio) {
		this.colegio = colegio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_orden_laboratorio", length = 22)
	public Date getFechaOrdenLaboratorio() {
		return this.fechaOrdenLaboratorio;
	}

	public void setFechaOrdenLaboratorio(Date fechaOrdenLaboratorio) {
		this.fechaOrdenLaboratorio = fechaOrdenLaboratorio;
	}

	@Column(name = "estado_carga", length = 1)
	public Character getEstadoCarga() {
		return this.estadoCarga;
	}

	public void setEstadoCarga(Character estadoCarga) {
		this.estadoCarga = estadoCarga;
	}

	@Column(name = "otro", length = 1)
	public Character getOtro() {
		return this.otro;
	}

	public void setOtro(Character otro) {
		this.otro = otro;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fis", length = 22)
	public Date getFis() {
		return this.fis;
	}

	public void setFis(Date fis) {
		this.fis = fis;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fif", length = 22)
	public Date getFif() {
		return this.fif;
	}

	public void setFif(Date fif) {
		this.fif = fif;
	}

	@Column(name = "hepatomegalia_cm", precision = 5)
	public BigDecimal getHepatomegaliaCm() {
		return this.hepatomegaliaCm;
	}

	public void setHepatomegaliaCm(BigDecimal hepatomegaliaCm) {
		this.hepatomegaliaCm = hepatomegaliaCm;
	}

	@Column(name = "eritrocitos", length = 1)
	public Character getEritrocitos() {
		return this.eritrocitos;
	}

	public void setEritrocitos(Character eritrocitos) {
		this.eritrocitos = eritrocitos;
	}

	@Column(name = "planes")
	public String getPlanes() {
		return this.planes;
	}

	public void setPlanes(String planes) {
		this.planes = planes;
	}

	@Column(name = "medico_cambio_turno")
	public Short getMedicoCambioTurno() {
		return this.medicoCambioTurno;
	}

	public void setMedicoCambioTurno(Short medicoCambioTurno) {
		this.medicoCambioTurno = medicoCambioTurno;
	}

	@Column(name = "hemoconc", length = 1)
	public Character getHemoconc() {
		return this.hemoconc;
	}

	public void setHemoconc(Character hemoconc) {
		this.hemoconc = hemoconc;
	}

	@Column(name = "vomito12h")
	public Short getVomito12h() {
		return this.vomito12h;
	}

	public void setVomito12h(Short vomito12h) {
		this.vomito12h = vomito12h;
	}

	@Column(name = "pad")
	public Short getPad() {
		return this.pad;
	}

	public void setPad(Short pad) {
		this.pad = pad;
	}

	@Column(name = "pas")
	public Short getPas() {
		return this.pas;
	}

	public void setPas(Short pas) {
		this.pas = pas;
	}

	@Column(name = "telef", precision = 10, scale = 0)
	public Long getTelef() {
		return this.telef;
	}

	public void setTelef(Long telef) {
		this.telef = telef;
	}

	@Column(name = "hora", length = 8)
	public String getHora() {
		return hora;
	}

	public void setHora(String hora) {
		this.hora = hora;
	}
	
	@Column(name = "horasv", length = 8)
	public String getHorasv() {
		return horasv;
	}

	public void setHorasv(String horasv) {
		this.horasv = horasv;
	}

	
	@Column(name = "no_atiende_llamado_enfermeria", length = 150)
	public String getNoAtiendeLlamadoEnfermeria() {
		return noAtiendeLlamadoEnfermeria;
	}

	public void setNoAtiendeLlamadoEnfermeria(String noAtiendeLlamadoEnfermeria) {
		this.noAtiendeLlamadoEnfermeria = noAtiendeLlamadoEnfermeria;
	}
	
	@Column(name = "no_atiende_llamado_medico", length = 150)
	public String getNoAtiendeLlamadoMedico() {
		return noAtiendeLlamadoMedico;
	}

	public void setNoAtiendeLlamadoMedico(String noAtiendeLlamadoMedico) {
		this.noAtiendeLlamadoMedico = noAtiendeLlamadoMedico;
	}
	
	@Column(name = "estudios_participantes")
	public String getEstudiosParticipantes() {
		return estudiosParticipantes;
	}

	public void setEstudiosParticipantes(String estudiosParticipantes) {
		this.estudiosParticipantes = estudiosParticipantes;
	}

	@Column(name = "uaf")
	public boolean isUaf() {
		return uaf;
	}

	public void setUaf(boolean uaf) {
		this.uaf = uaf;
	}
	
	@Column(name = "repeat_key", length = 10)
	public String getRepeatKey() {
		return repeatKey;
	}

	public void setRepeatKey(String repeatKey) {
		this.repeatKey = repeatKey;
	}
	
	@Column(name = "cv", length = 1)
	public Character getCv() {
		return this.cV;
	}

	public void setCv(Character cV) {
		this.cV = cV;
	}
	
	@Column(name = "consulta_respiratorio")
	public Character getConsultaRespiratorio() {
		return consultaRespiratorio;
	}

	public void setConsultaRespiratorio(Character consultaRespiratorio) {
		this.consultaRespiratorio = consultaRespiratorio;
	}

	@Column(name = "usuario_cierra_hoja", nullable = true)
	public Short getUsuarioCierraHoja() {
		return usuarioCierraHoja;
	}

	public void setUsuarioCierraHoja(Short usuarioCierraHoja) {
		this.usuarioCierraHoja = usuarioCierraHoja;
	}

	@Column(name = "hoja_impresa", length = 1)
	public Character getHojaImpresa() {
		return hojaImpresa;
	}

	public void setHojaImpresa(Character hojaImpresa) {
		this.hojaImpresa = hojaImpresa;
	}

	public boolean isDigitada() {
		return digitada;
	}

	public void setDigitada(boolean digitada) {
		this.digitada = digitada;
	}
	
	@Column(name = "supervisor", nullable = true)
	public Short getSupervisor() {
		return supervisor;
	}

	public void setSupervisor(Short supervisor) {
		this.supervisor = supervisor;
	}

	@Column(name = "offline")
	public boolean isOffline() {
		return offline;
	}

	public void setOffline(boolean offline) {
		this.offline = offline;
	}
}
