package ni.com.sts.estudioCohorteCSSFV.modelo;

// Generated Oct 2, 2015 2:04:34 PM by Hibernate Tools 4.0.0
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MalariaResultados generated by hbm2java
 */
@Entity
@Table(name = "malaria_resultados")
public class MalariaResultados implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int secMalariaResultado;
	private int secOrdenLaboratorio;
	private Boolean PFalciparum;
	private Boolean PVivax;
	private Boolean negativo;
	private String codigoMuestra;
	private Short usuarioBioanalista;
	private Date horaReporte;
	private Character estado;

	public MalariaResultados() {
	}

	public MalariaResultados(int secMalariaResultado, int secOrdenLaboratorio) {
		this.secMalariaResultado = secMalariaResultado;
		this.secOrdenLaboratorio = secOrdenLaboratorio;
	}

	public MalariaResultados(int secMalariaResultado, int secOrdenLaboratorio,
			Boolean PFalciparum, Boolean PVivax, Boolean negativo,
			String codigoMuestra, Short usuarioBioanalista, Date horaReporte,
			Character estado) {
		this.secMalariaResultado = secMalariaResultado;
		this.secOrdenLaboratorio = secOrdenLaboratorio;
		this.PFalciparum = PFalciparum;
		this.PVivax = PVivax;
		this.negativo = negativo;
		this.codigoMuestra = codigoMuestra;
		this.usuarioBioanalista = usuarioBioanalista;
		this.horaReporte = horaReporte;
		this.estado = estado;
	}

	@Id
	@SequenceGenerator(name = "id_msp_malaria_resultado_sec", sequenceName = "malaria_resultados_sec_malaria_resultado_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "id_msp_malaria_resultado_sec")
	@Column(name = "sec_malaria_resultado", unique = true, nullable = false)
	public int getSecMalariaResultado() {
		return this.secMalariaResultado;
	}

	public void setSecMalariaResultado(int secMalariaResultado) {
		this.secMalariaResultado = secMalariaResultado;
	}

	@Column(name = "sec_orden_laboratorio", nullable = false)
	public int getSecOrdenLaboratorio() {
		return this.secOrdenLaboratorio;
	}

	public void setSecOrdenLaboratorio(int secOrdenLaboratorio) {
		this.secOrdenLaboratorio = secOrdenLaboratorio;
	}

	@Column(name = "p_falciparum", length = 8)
	public Boolean getPFalciparum() {
		return this.PFalciparum;
	}

	public void setPFalciparum(Boolean PFalciparum) {
		this.PFalciparum = PFalciparum;
	}

	@Column(name = "p_vivax", length = 8)
	public Boolean getPVivax() {
		return this.PVivax;
	}

	public void setPVivax(Boolean PVivax) {
		this.PVivax = PVivax;
	}

	@Column(name = "negativo", length = 8)
	public Boolean getNegativo() {
		return this.negativo;
	}

	public void setNegativo(Boolean negativo) {
		this.negativo = negativo;
	}

	@Column(name = "codigo_muestra", length = 50)
	public String getCodigoMuestra() {
		return this.codigoMuestra;
	}

	public void setCodigoMuestra(String codigoMuestra) {
		this.codigoMuestra = codigoMuestra;
	}

	@Column(name = "usuario_bioanalista")
	public Short getUsuarioBioanalista() {
		return this.usuarioBioanalista;
	}

	public void setUsuarioBioanalista(Short usuarioBioanalista) {
		this.usuarioBioanalista = usuarioBioanalista;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "hora_reporte", length = 29)
	public Date getHoraReporte() {
		return this.horaReporte;
	}

	public void setHoraReporte(Date horaReporte) {
		this.horaReporte = horaReporte;
	}

	@Column(name = "estado", length = 1)
	public Character getEstado() {
		return this.estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

}

