package ni.com.sts.estudioCohorteCSSFV.modelo;

// Generated Oct 2, 2015 2:04:34 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MalariaResultadosId generated by hbm2java
 */
@Embeddable
public class MalariaResultadosId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int secMalariaResultado;
	private int secOrdenLaboratorio;
	private String codigoMuestra;
	private Short usuarioBioanalista;
	private Date horaReporte;
	private Character estado;
	private Boolean PFalciparum;
	private Boolean PVivax;
	private Boolean negativo;

	public MalariaResultadosId() {
	}

	public MalariaResultadosId(int secMalariaResultado, int secOrdenLaboratorio) {
		this.secMalariaResultado = secMalariaResultado;
		this.secOrdenLaboratorio = secOrdenLaboratorio;
	}

	public MalariaResultadosId(int secMalariaResultado,
			int secOrdenLaboratorio, String codigoMuestra,
			Short usuarioBioanalista, Date horaReporte, Character estado,
			Boolean PFalciparum, Boolean PVivax, Boolean negativo) {
		this.secMalariaResultado = secMalariaResultado;
		this.secOrdenLaboratorio = secOrdenLaboratorio;
		this.codigoMuestra = codigoMuestra;
		this.usuarioBioanalista = usuarioBioanalista;
		this.horaReporte = horaReporte;
		this.estado = estado;
		this.PFalciparum = PFalciparum;
		this.PVivax = PVivax;
		this.negativo = negativo;
	}

	@Column(name = "sec_malaria_resultado", unique = true, nullable = false)
	public int getSecMalariaResultado() {
		return this.secMalariaResultado;
	}

	public void setSecMalariaResultado(int secMalariaResultado) {
		this.secMalariaResultado = secMalariaResultado;
	}

	@Column(name = "sec_orden_laboratorio", nullable = false)
	public int getSecOrdenLaboratorio() {
		return this.secOrdenLaboratorio;
	}

	public void setSecOrdenLaboratorio(int secOrdenLaboratorio) {
		this.secOrdenLaboratorio = secOrdenLaboratorio;
	}

	@Column(name = "codigo_muestra", length = 50)
	public String getCodigoMuestra() {
		return this.codigoMuestra;
	}

	public void setCodigoMuestra(String codigoMuestra) {
		this.codigoMuestra = codigoMuestra;
	}

	@Column(name = "usuario_bioanalista")
	public Short getUsuarioBioanalista() {
		return this.usuarioBioanalista;
	}

	public void setUsuarioBioanalista(Short usuarioBioanalista) {
		this.usuarioBioanalista = usuarioBioanalista;
	}

	@Column(name = "hora_reporte", length = 29)
	public Date getHoraReporte() {
		return this.horaReporte;
	}

	public void setHoraReporte(Date horaReporte) {
		this.horaReporte = horaReporte;
	}

	@Column(name = "estado", length = 1)
	public Character getEstado() {
		return this.estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

	@Column(name = "p_falciparum")
	public Boolean getPFalciparum() {
		return this.PFalciparum;
	}

	public void setPFalciparum(Boolean PFalciparum) {
		this.PFalciparum = PFalciparum;
	}

	@Column(name = "p_vivax")
	public Boolean getPVivax() {
		return this.PVivax;
	}

	public void setPVivax(Boolean PVivax) {
		this.PVivax = PVivax;
	}

	@Column(name = "negativo")
	public Boolean getNegativo() {
		return this.negativo;
	}

	public void setNegativo(Boolean negativo) {
		this.negativo = negativo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MalariaResultadosId))
			return false;
		MalariaResultadosId castOther = (MalariaResultadosId) other;

		return (this.getSecMalariaResultado() == castOther
				.getSecMalariaResultado())
				&& (this.getSecOrdenLaboratorio() == castOther
						.getSecOrdenLaboratorio())
				&& ((this.getCodigoMuestra() == castOther.getCodigoMuestra()) || (this
						.getCodigoMuestra() != null
						&& castOther.getCodigoMuestra() != null && this
						.getCodigoMuestra()
						.equals(castOther.getCodigoMuestra())))
				&& ((this.getUsuarioBioanalista() == castOther
						.getUsuarioBioanalista()) || (this
						.getUsuarioBioanalista() != null
						&& castOther.getUsuarioBioanalista() != null && this
						.getUsuarioBioanalista().equals(
								castOther.getUsuarioBioanalista())))
				&& ((this.getHoraReporte() == castOther.getHoraReporte()) || (this
						.getHoraReporte() != null
						&& castOther.getHoraReporte() != null && this
						.getHoraReporte().equals(castOther.getHoraReporte())))
				&& ((this.getEstado() == castOther.getEstado()) || (this
						.getEstado() != null && castOther.getEstado() != null && this
						.getEstado().equals(castOther.getEstado())))
				&& ((this.getPFalciparum() == castOther.getPFalciparum()) || (this
						.getPFalciparum() != null
						&& castOther.getPFalciparum() != null && this
						.getPFalciparum().equals(castOther.getPFalciparum())))
				&& ((this.getPVivax() == castOther.getPVivax()) || (this
						.getPVivax() != null && castOther.getPVivax() != null && this
						.getPVivax().equals(castOther.getPVivax())))
				&& ((this.getNegativo() == castOther.getNegativo()) || (this
						.getNegativo() != null
						&& castOther.getNegativo() != null && this
						.getNegativo().equals(castOther.getNegativo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSecMalariaResultado();
		result = 37 * result + this.getSecOrdenLaboratorio();
		result = 37
				* result
				+ (getCodigoMuestra() == null ? 0 : this.getCodigoMuestra()
						.hashCode());
		result = 37
				* result
				+ (getUsuarioBioanalista() == null ? 0 : this
						.getUsuarioBioanalista().hashCode());
		result = 37
				* result
				+ (getHoraReporte() == null ? 0 : this.getHoraReporte()
						.hashCode());
		result = 37 * result
				+ (getEstado() == null ? 0 : this.getEstado().hashCode());
		result = 37
				* result
				+ (getPFalciparum() == null ? 0 : this.getPFalciparum()
						.hashCode());
		result = 37 * result
				+ (getPVivax() == null ? 0 : this.getPVivax().hashCode());
		result = 37 * result
				+ (getNegativo() == null ? 0 : this.getNegativo().hashCode());
		return result;
	}

}
