package ni.com.sts.estudioCohorteCSSFV.modelo;
// Generated 04-30-2019 09:50:59 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Municipios generated by hbm2java
 */
@Entity
@Table(name = "municipios")
public class Municipios implements java.io.Serializable {

	private int divisionpoliticaId;
	private String nombre;
	private int codigoNacional;
	private int dependencia;

	public Municipios() {
	}

	public Municipios(int divisionpoliticaId, String nombre, int codigoNacional, int dependencia) {
		this.divisionpoliticaId = divisionpoliticaId;
		this.nombre = nombre;
		this.codigoNacional = codigoNacional;
		this.dependencia = dependencia;
	}

	@Id

	@Column(name = "divisionpolitica_id", unique = true, nullable = false)
	public int getDivisionpoliticaId() {
		return this.divisionpoliticaId;
	}

	public void setDivisionpoliticaId(int divisionpoliticaId) {
		this.divisionpoliticaId = divisionpoliticaId;
	}

	@Column(name = "nombre", nullable = false, length = 64)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "codigo_nacional", nullable = false)
	public int getCodigoNacional() {
		return this.codigoNacional;
	}

	public void setCodigoNacional(int codigoNacional) {
		this.codigoNacional = codigoNacional;
	}

	@Column(name = "dependencia", nullable = false)
	public int getDependencia() {
		return this.dependencia;
	}

	public void setDependencia(int dependencia) {
		this.dependencia = dependencia;
	}

}
