package ni.com.sts.estudioCohorteCSSFV.modelo;

// Generated 26-feb-2015 20:57:39 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Paciente generated by hbm2java
 */
@Entity
@Table(name = "paciente", uniqueConstraints = @UniqueConstraint(columnNames = "sec_paciente"))
public class Paciente implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6778485401094003464L;
	private int codExpediente;
	private int secPaciente;
	private String nombre1;
	private String nombre2;
	private String apellido1;
	private String apellido2;
	private char sexo;
	private String direccion;
	private String telefono;
	private Date fechaNac;
	private Short edad;
	private Character estudiante;
	private Character turno;
	private Short escuela;
	private String tutorNombre1;
	private String tutorNombre2;
	private String tutorApellido1;
	private String tutorApellido2;
	private String telefono2;
	private String telefono3;
	private Character retirado;

	public Paciente() {
	}

	public Paciente(int codExpediente, int secPaciente, String nombre1,
			String apellido1, char sexo, String direccion) {
		this.codExpediente = codExpediente;
		this.secPaciente = secPaciente;
		this.nombre1 = nombre1;
		this.apellido1 = apellido1;
		this.sexo = sexo;
		this.direccion = direccion;
	}

	public Paciente(int codExpediente, int secPaciente, String nombre1,
			String nombre2, String apellido1, String apellido2, char sexo,
			String direccion, String telefono, Date fechaNac, Short edad,
			Character estudiante, Character turno, Short escuela,
			String tutorNombre1, String tutorNombre2, String tutorApellido1,
			String tutorApellido2, String telefono2, String telefono3, Character retirado) {
		this.codExpediente = codExpediente;
		this.secPaciente = secPaciente;
		this.nombre1 = nombre1;
		this.nombre2 = nombre2;
		this.apellido1 = apellido1;
		this.apellido2 = apellido2;
		this.sexo = sexo;
		this.direccion = direccion;
		this.telefono = telefono;
		this.fechaNac = fechaNac;
		this.edad = edad;
		this.estudiante = estudiante;
		this.turno = turno;
		this.escuela = escuela;
		this.tutorNombre1 = tutorNombre1;
		this.tutorNombre2 = tutorNombre2;
		this.tutorApellido1 = tutorApellido1;
		this.tutorApellido2 = tutorApellido2;
		this.telefono2 = telefono2;
		this.telefono3 = telefono3;
		this.retirado = retirado;
	}

	@Id
	@Column(name = "cod_expediente", unique = true, nullable = false)
	public int getCodExpediente() {
		return this.codExpediente;
	}

	public void setCodExpediente(int codExpediente) {
		this.codExpediente = codExpediente;
	}

	@Column(name = "sec_paciente", unique = true, nullable = false)
	public int getSecPaciente() {
		return this.secPaciente;
	}

	public void setSecPaciente(int secPaciente) {
		this.secPaciente = secPaciente;
	}

	@Column(name = "nombre1", nullable = false, length = 32)
	public String getNombre1() {
		return this.nombre1;
	}

	public void setNombre1(String nombre1) {
		this.nombre1 = nombre1;
	}

	@Column(name = "nombre2", length = 32)
	public String getNombre2() {
		return this.nombre2;
	}

	public void setNombre2(String nombre2) {
		this.nombre2 = nombre2;
	}

	@Column(name = "apellido1", nullable = false, length = 32)
	public String getApellido1() {
		return this.apellido1;
	}

	public void setApellido1(String apellido1) {
		this.apellido1 = apellido1;
	}

	@Column(name = "apellido2", length = 32)
	public String getApellido2() {
		return this.apellido2;
	}

	public void setApellido2(String apellido2) {
		this.apellido2 = apellido2;
	}

	@Column(name = "sexo", nullable = false, length = 1)
	public char getSexo() {
		return this.sexo;
	}

	public void setSexo(char sexo) {
		this.sexo = sexo;
	}

	@Column(name = "direccion", nullable = false, length = 256)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "telefono", length = 32)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_nac", length = 13)
	public Date getFechaNac() {
		return this.fechaNac;
	}

	public void setFechaNac(Date fechaNac) {
		this.fechaNac = fechaNac;
	}

	@Column(name = "edad")
	public Short getEdad() {
		return this.edad;
	}

	public void setEdad(Short edad) {
		this.edad = edad;
	}

	@Column(name = "estudiante", length = 1)
	public Character getEstudiante() {
		return this.estudiante;
	}

	public void setEstudiante(Character estudiante) {
		this.estudiante = estudiante;
	}

	@Column(name = "turno", length = 1)
	public Character getTurno() {
		return this.turno;
	}

	public void setTurno(Character turno) {
		this.turno = turno;
	}

	@Column(name = "escuela")
	public Short getEscuela() {
		return this.escuela;
	}

	public void setEscuela(Short escuela) {
		this.escuela = escuela;
	}

	@Column(name = "tutor_nombre1", length = 32)
	public String getTutorNombre1() {
		return this.tutorNombre1;
	}

	public void setTutorNombre1(String tutorNombre1) {
		this.tutorNombre1 = tutorNombre1;
	}

	@Column(name = "tutor_nombre2", length = 32)
	public String getTutorNombre2() {
		return this.tutorNombre2;
	}

	public void setTutorNombre2(String tutorNombre2) {
		this.tutorNombre2 = tutorNombre2;
	}

	@Column(name = "tutor_apellido1", length = 32)
	public String getTutorApellido1() {
		return this.tutorApellido1;
	}

	public void setTutorApellido1(String tutorApellido1) {
		this.tutorApellido1 = tutorApellido1;
	}

	@Column(name = "tutor_apellido2", length = 32)
	public String getTutorApellido2() {
		return this.tutorApellido2;
	}

	public void setTutorApellido2(String tutorApellido2) {
		this.tutorApellido2 = tutorApellido2;
	}

	@Column(name = "telefono2", length = 32)
	public String getTelefono2() {
		return this.telefono2;
	}

	public void setTelefono2(String telefono2) {
		this.telefono2 = telefono2;
	}

	@Column(name = "telefono3", length = 32)
	public String getTelefono3() {
		return this.telefono3;
	}

	public void setTelefono3(String telefono3) {
		this.telefono3 = telefono3;
	}
	
	@Column(name = "retirado", length = 1)
	public Character getRetirado() {
		return this.retirado;
	}

	public void setRetirado(Character retirado) {
		this.retirado = retirado;
	}
}
