package ni.com.sts.estudioCohorteCSSFV.modelo;

// Generated 26-feb-2015 20:57:39 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PerifericoResultadoId generated by hbm2java
 */
@Embeddable
public class PerifericoResultadoId implements java.io.Serializable {

	private int secPerifericoResultado;
	private int secOrdenLaboratorio;
	private String anisocitosis;
	private String anisocromia;
	private String poiquilocitosis;
	private String linfocitosAtipicos;
	private String observacionSblanca;
	private String observacionPlaqueta;
	private String codigoMuestra;
	private Short usuarioBioanalista;
	private Date horaReporte;
	private Character estado;

	public PerifericoResultadoId() {
	}

	public PerifericoResultadoId(int secPerifericoResultado,
			int secOrdenLaboratorio) {
		this.secPerifericoResultado = secPerifericoResultado;
		this.secOrdenLaboratorio = secOrdenLaboratorio;
	}

	public PerifericoResultadoId(int secPerifericoResultado,
			int secOrdenLaboratorio, String anisocitosis, String anisocromia,
			String poiquilocitosis, String linfocitosAtipicos,
			String observacionSblanca, String observacionPlaqueta,
			String codigoMuestra, Short usuarioBioanalista, Date horaReporte,
			Character estado) {
		this.secPerifericoResultado = secPerifericoResultado;
		this.secOrdenLaboratorio = secOrdenLaboratorio;
		this.anisocitosis = anisocitosis;
		this.anisocromia = anisocromia;
		this.poiquilocitosis = poiquilocitosis;
		this.linfocitosAtipicos = linfocitosAtipicos;
		this.observacionSblanca = observacionSblanca;
		this.observacionPlaqueta = observacionPlaqueta;
		this.codigoMuestra = codigoMuestra;
		this.usuarioBioanalista = usuarioBioanalista;
		this.horaReporte = horaReporte;
		this.estado = estado;
	}

	@Column(name = "sec_periferico_resultado", unique = true, nullable = false)
	public int getSecPerifericoResultado() {
		return this.secPerifericoResultado;
	}

	public void setSecPerifericoResultado(int secPerifericoResultado) {
		this.secPerifericoResultado = secPerifericoResultado;
	}

	@Column(name = "sec_orden_laboratorio", nullable = false)
	public int getSecOrdenLaboratorio() {
		return this.secOrdenLaboratorio;
	}

	public void setSecOrdenLaboratorio(int secOrdenLaboratorio) {
		this.secOrdenLaboratorio = secOrdenLaboratorio;
	}

	@Column(name = "anisocitosis", length = 32)
	public String getAnisocitosis() {
		return this.anisocitosis;
	}

	public void setAnisocitosis(String anisocitosis) {
		this.anisocitosis = anisocitosis;
	}

	@Column(name = "anisocromia", length = 32)
	public String getAnisocromia() {
		return this.anisocromia;
	}

	public void setAnisocromia(String anisocromia) {
		this.anisocromia = anisocromia;
	}

	@Column(name = "poiquilocitosis", length = 124)
	public String getPoiquilocitosis() {
		return this.poiquilocitosis;
	}

	public void setPoiquilocitosis(String poiquilocitosis) {
		this.poiquilocitosis = poiquilocitosis;
	}

	@Column(name = "linfocitos_atipicos", length = 32)
	public String getLinfocitosAtipicos() {
		return this.linfocitosAtipicos;
	}

	public void setLinfocitosAtipicos(String linfocitosAtipicos) {
		this.linfocitosAtipicos = linfocitosAtipicos;
	}

	@Column(name = "observacion_sblanca", length = 64)
	public String getObservacionSblanca() {
		return this.observacionSblanca;
	}

	public void setObservacionSblanca(String observacionSblanca) {
		this.observacionSblanca = observacionSblanca;
	}

	@Column(name = "observacion_plaqueta", length = 64)
	public String getObservacionPlaqueta() {
		return this.observacionPlaqueta;
	}

	public void setObservacionPlaqueta(String observacionPlaqueta) {
		this.observacionPlaqueta = observacionPlaqueta;
	}

	@Column(name = "codigo_muestra", length = 50)
	public String getCodigoMuestra() {
		return this.codigoMuestra;
	}

	public void setCodigoMuestra(String codigoMuestra) {
		this.codigoMuestra = codigoMuestra;
	}

	@Column(name = "usuario_bioanalista")
	public Short getUsuarioBioanalista() {
		return this.usuarioBioanalista;
	}

	public void setUsuarioBioanalista(Short usuarioBioanalista) {
		this.usuarioBioanalista = usuarioBioanalista;
	}

	@Column(name = "hora_reporte", length = 29)
	public Date getHoraReporte() {
		return this.horaReporte;
	}

	public void setHoraReporte(Date horaReporte) {
		this.horaReporte = horaReporte;
	}

	@Column(name = "estado", length = 1)
	public Character getEstado() {
		return this.estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PerifericoResultadoId))
			return false;
		PerifericoResultadoId castOther = (PerifericoResultadoId) other;

		return (this.getSecPerifericoResultado() == castOther
				.getSecPerifericoResultado())
				&& (this.getSecOrdenLaboratorio() == castOther
						.getSecOrdenLaboratorio())
				&& ((this.getAnisocitosis() == castOther.getAnisocitosis()) || (this
						.getAnisocitosis() != null
						&& castOther.getAnisocitosis() != null && this
						.getAnisocitosis().equals(castOther.getAnisocitosis())))
				&& ((this.getAnisocromia() == castOther.getAnisocromia()) || (this
						.getAnisocromia() != null
						&& castOther.getAnisocromia() != null && this
						.getAnisocromia().equals(castOther.getAnisocromia())))
				&& ((this.getPoiquilocitosis() == castOther
						.getPoiquilocitosis()) || (this.getPoiquilocitosis() != null
						&& castOther.getPoiquilocitosis() != null && this
						.getPoiquilocitosis().equals(
								castOther.getPoiquilocitosis())))
				&& ((this.getLinfocitosAtipicos() == castOther
						.getLinfocitosAtipicos()) || (this
						.getLinfocitosAtipicos() != null
						&& castOther.getLinfocitosAtipicos() != null && this
						.getLinfocitosAtipicos().equals(
								castOther.getLinfocitosAtipicos())))
				&& ((this.getObservacionSblanca() == castOther
						.getObservacionSblanca()) || (this
						.getObservacionSblanca() != null
						&& castOther.getObservacionSblanca() != null && this
						.getObservacionSblanca().equals(
								castOther.getObservacionSblanca())))
				&& ((this.getObservacionPlaqueta() == castOther
						.getObservacionPlaqueta()) || (this
						.getObservacionPlaqueta() != null
						&& castOther.getObservacionPlaqueta() != null && this
						.getObservacionPlaqueta().equals(
								castOther.getObservacionPlaqueta())))
				&& ((this.getCodigoMuestra() == castOther.getCodigoMuestra()) || (this
						.getCodigoMuestra() != null
						&& castOther.getCodigoMuestra() != null && this
						.getCodigoMuestra()
						.equals(castOther.getCodigoMuestra())))
				&& ((this.getUsuarioBioanalista() == castOther
						.getUsuarioBioanalista()) || (this
						.getUsuarioBioanalista() != null
						&& castOther.getUsuarioBioanalista() != null && this
						.getUsuarioBioanalista().equals(
								castOther.getUsuarioBioanalista())))
				&& ((this.getHoraReporte() == castOther.getHoraReporte()) || (this
						.getHoraReporte() != null
						&& castOther.getHoraReporte() != null && this
						.getHoraReporte().equals(castOther.getHoraReporte())))
				&& ((this.getEstado() == castOther.getEstado()) || (this
						.getEstado() != null && castOther.getEstado() != null && this
						.getEstado().equals(castOther.getEstado())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSecPerifericoResultado();
		result = 37 * result + this.getSecOrdenLaboratorio();
		result = 37
				* result
				+ (getAnisocitosis() == null ? 0 : this.getAnisocitosis()
						.hashCode());
		result = 37
				* result
				+ (getAnisocromia() == null ? 0 : this.getAnisocromia()
						.hashCode());
		result = 37
				* result
				+ (getPoiquilocitosis() == null ? 0 : this.getPoiquilocitosis()
						.hashCode());
		result = 37
				* result
				+ (getLinfocitosAtipicos() == null ? 0 : this
						.getLinfocitosAtipicos().hashCode());
		result = 37
				* result
				+ (getObservacionSblanca() == null ? 0 : this
						.getObservacionSblanca().hashCode());
		result = 37
				* result
				+ (getObservacionPlaqueta() == null ? 0 : this
						.getObservacionPlaqueta().hashCode());
		result = 37
				* result
				+ (getCodigoMuestra() == null ? 0 : this.getCodigoMuestra()
						.hashCode());
		result = 37
				* result
				+ (getUsuarioBioanalista() == null ? 0 : this
						.getUsuarioBioanalista().hashCode());
		result = 37
				* result
				+ (getHoraReporte() == null ? 0 : this.getHoraReporte()
						.hashCode());
		result = 37 * result
				+ (getEstado() == null ? 0 : this.getEstado().hashCode());
		return result;
	}

}
