package ni.com.sts.estudioCohorteCSSFV.modelo;

// Generated 26-feb-2015 20:57:39 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * SeguimientoInfluenza generated by hbm2java
 */
@Entity
@Table(name = "seguimiento_influenza", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "sec_seg_influenza"))
public class SeguimientoInfluenza implements java.io.Serializable {

	private int secHojaInfluenza;
	private int secSegInfluenza;
	private int controlDia;
	private Date fechaSeguimiento;
	private short usuarioMedico;
	private String consultaInicial;
	private String fiebre;
	private String tos;
	private String secrecionNasal;
	private String dolorGarganta;
	private String congestionNasa;
	private String dolorCabeza;
	private String faltaApetito;
	private String dolorMuscular;
	private String dolorArticular;
	private String dolorOido;
	private String respiracionRapida;
	private String dificultadRespirar;
	private String faltaEscuela;
	private String quedoEnCama;

	public SeguimientoInfluenza() {
	}

	public SeguimientoInfluenza(int secHojaInfluenza, int secSegInfluenza,
			char controlDia, Date fechaSeguimiento, short usuarioMedico,
			String consultaInicial, String fiebre, String tos, String secrecionNasal,
			String dolorGarganta, String congestionNasa, String dolorCabeza,
			String faltaApetito, String dolorMuscular, String dolorArticular,
			String dolorOido, String respiracionRapida, String dificultadRespirar,
			String faltaEscuela, String quedoEnCama) {
		this.secHojaInfluenza = secHojaInfluenza;
		this.secSegInfluenza = secSegInfluenza;
		this.controlDia = controlDia;
		this.fechaSeguimiento = fechaSeguimiento;
		this.usuarioMedico = usuarioMedico;
		this.consultaInicial = consultaInicial;
		this.fiebre = fiebre;
		this.tos = tos;
		this.secrecionNasal = secrecionNasal;
		this.dolorGarganta = dolorGarganta;
		this.congestionNasa = congestionNasa;
		this.dolorCabeza = dolorCabeza;
		this.faltaApetito = faltaApetito;
		this.dolorMuscular = dolorMuscular;
		this.dolorArticular = dolorArticular;
		this.dolorOido = dolorOido;
		this.respiracionRapida = respiracionRapida;
		this.dificultadRespirar = dificultadRespirar;
		this.faltaEscuela = faltaEscuela;
		this.quedoEnCama = quedoEnCama;
	}

	@Column(name = "sec_hoja_influenza", nullable = false)
	public int getSecHojaInfluenza() {
		return this.secHojaInfluenza;
	}

	public void setSecHojaInfluenza(int secHojaInfluenza) {
		this.secHojaInfluenza = secHojaInfluenza;
	}

	@Id
	@SequenceGenerator(name = "id_seg_influenza_sec", sequenceName = "seguimiento_influenza_sec_seg_influenza_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "id_seg_influenza_sec")
	@Column(name = "sec_seg_influenza", unique = true, nullable = false)
	public int getSecSegInfluenza() {
		return this.secSegInfluenza;
	}

	public void setSecSegInfluenza(int secSegInfluenza) {
		this.secSegInfluenza = secSegInfluenza;
	}

	@Column(name = "control_dia", nullable = false, length = 1)
	public int getControlDia() {
		return controlDia;
	}

	public void setControlDia(int controlDia) {
		this.controlDia = controlDia;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_seguimiento", nullable = false, length = 13)
	public Date getFechaSeguimiento() {
		return this.fechaSeguimiento;
	}


	public void setFechaSeguimiento(Date fechaSeguimiento) {
		this.fechaSeguimiento = fechaSeguimiento;
	}

	@Column(name = "usuario_medico", nullable = false)
	public short getUsuarioMedico() {
		return this.usuarioMedico;
	}

	public void setUsuarioMedico(short usuarioMedico) {
		this.usuarioMedico = usuarioMedico;
	}

	@Column(name = "consulta_inicial", nullable = false, length = 2)
	public String getConsultaInicial() {
		return this.consultaInicial;
	}

	public void setConsultaInicial(String consultaInicial) {
		this.consultaInicial = consultaInicial;
	}

	@Column(name = "fiebre", nullable = false, length = 2)
	public String getFiebre() {
		return this.fiebre;
	}

	public void setFiebre(String fiebre) {
		this.fiebre = fiebre;
	}

	@Column(name = "tos", nullable = false, length = 2)
	public String getTos() {
		return this.tos;
	}

	public void setTos(String tos) {
		this.tos = tos;
	}

	@Column(name = "secrecion_nasal", nullable = false, length = 2)
	public String getSecrecionNasal() {
		return this.secrecionNasal;
	}

	public void setSecrecionNasal(String secrecionNasal) {
		this.secrecionNasal = secrecionNasal;
	}

	@Column(name = "dolor_garganta", nullable = false, length = 2)
	public String getDolorGarganta() {
		return this.dolorGarganta;
	}

	public void setDolorGarganta(String dolorGarganta) {
		this.dolorGarganta = dolorGarganta;
	}

	@Column(name = "congestion_nasa", nullable = false, length = 2)
	public String getCongestionNasa() {
		return this.congestionNasa;
	}

	public void setCongestionNasa(String congestionNasa) {
		this.congestionNasa = congestionNasa;
	}

	@Column(name = "dolor_cabeza", nullable = false, length = 2)
	public String getDolorCabeza() {
		return this.dolorCabeza;
	}

	public void setDolorCabeza(String dolorCabeza) {
		this.dolorCabeza = dolorCabeza;
	}

	@Column(name = "falta_apetito", nullable = false, length = 2)
	public String getFaltaApetito() {
		return this.faltaApetito;
	}

	public void setFaltaApetito(String faltaApetito) {
		this.faltaApetito = faltaApetito;
	}

	@Column(name = "dolor_muscular", nullable = false, length = 2)
	public String getDolorMuscular() {
		return this.dolorMuscular;
	}

	public void setDolorMuscular(String dolorMuscular) {
		this.dolorMuscular = dolorMuscular;
	}

	@Column(name = "dolor_articular", nullable = false, length = 2)
	public String getDolorArticular() {
		return this.dolorArticular;
	}

	public void setDolorArticular(String dolorArticular) {
		this.dolorArticular = dolorArticular;
	}

	@Column(name = "dolor_oido", nullable = false, length = 2)
	public String getDolorOido() {
		return this.dolorOido;
	}

	public void setDolorOido(String dolorOido) {
		this.dolorOido = dolorOido;
	}

	@Column(name = "respiracion_rapida", nullable = false, length = 2)
	public String getRespiracionRapida() {
		return this.respiracionRapida;
	}

	public void setRespiracionRapida(String respiracionRapida) {
		this.respiracionRapida = respiracionRapida;
	}

	@Column(name = "dificultad_respirar", nullable = false, length = 2)
	public String getDificultadRespirar() {
		return this.dificultadRespirar;
	}

	public void setDificultadRespirar(String dificultadRespirar) {
		this.dificultadRespirar = dificultadRespirar;
	}

	@Column(name = "falta_escuela", nullable = false, length = 2)
	public String getFaltaEscuela() {
		return this.faltaEscuela;
	}

	public void setFaltaEscuela(String faltaEscuela) {
		this.faltaEscuela = faltaEscuela;
	}

	@Column(name = "quedo_en_cama", nullable = false, length = 2)
	public String getQuedoEnCama() {
		return this.quedoEnCama;
	}

	public void setQuedoEnCama(String quedoEnCama) {
		this.quedoEnCama = quedoEnCama;
	}

}
