package ni.com.sts.estudioCohorteCSSFV.modelo;

// Generated 26-feb-2015 20:57:39 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * SeguimientoInfluenza generated by hbm2java
 */
@Entity
@Table(name = "seguimiento_influenza", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "sec_seg_influenza"))
public class SeguimientoInfluenza implements java.io.Serializable {

	private int secHojaInfluenza;
	private int secSegInfluenza;
	private int controlDia;
	private Date fechaSeguimiento;
	private short usuarioMedico;
	private String consultaInicial;
	private String fiebre;
	private String tos;
	private String secrecionNasal;
	private String dolorGarganta;
	private String congestionNasa;
	private String dolorCabeza;
	private String faltaApetito;
	private String dolorMuscular;
	private String dolorArticular;
	private String dolorOido;
	private String respiracionRapida;
	private String dificultadRespirar;
	private String faltaEscuela;
	private String quedoEnCama;
	
	/*Nuevos campos agregados 24/09/2019*/
	private String fiebreLeve;
	private String fiebreModerada;
	private String fiebreSevera;
	private String tosLeve;
	private String tosModerada;
	private String tosSevera;
	private String secrecionNasalLeve;
	private String secrecionNasalModerada;
	private String secrecionNasalSevera;
	private String dolorGargantaLeve;
	private String dolorGargantaModerada;
	private String dolorGargantaSevera;
	private String dolorCabezaLeve;
	private String dolorCabezaModerada;
	private String dolorCabezaSevera;
	private String dolorMuscularLeve;
	private String dolorMuscularModerada;
	private String dolorMuscularSevera;
	private String dolorArticularLeve;
	private String dolorArticularModerada;
	private String dolorArticularSevera;

	public SeguimientoInfluenza() {
	}

	public SeguimientoInfluenza(int secHojaInfluenza, int secSegInfluenza,
			char controlDia, Date fechaSeguimiento, short usuarioMedico,
			String consultaInicial, String fiebre, String tos, String secrecionNasal,
			String dolorGarganta, String congestionNasa, String dolorCabeza,
			String faltaApetito, String dolorMuscular, String dolorArticular,
			String dolorOido, String respiracionRapida, String dificultadRespirar,
			String faltaEscuela, String quedoEnCama ,
			/*Nuevos campos agregados 24/09/2019*/
			String fiebreLeve, String fiebreModerada, String fiebreSevera, 
			String tosLeve, String tosModerada, String tosSevera, 
			String secrecionNasalLeve, String secrecionNasalModerada, String secrecionNasalSevera,
			String dolorGargantaLeve, String dolorGargantaModerada, String dolorGargantaSevera, 
			String dolorCabezaLeve, String dolorCabezaModerada, String dolorCabezaSevera, 
			String dolorMuscularLeve, String dolorMuscularModerada, String dolorMuscularSevera, 
			String dolorArticularLeve, String dolorArticularModerada, String dolorArticularSevera) {
		this.secHojaInfluenza = secHojaInfluenza;
		this.secSegInfluenza = secSegInfluenza;
		this.controlDia = controlDia;
		this.fechaSeguimiento = fechaSeguimiento;
		this.usuarioMedico = usuarioMedico;
		this.consultaInicial = consultaInicial;
		this.fiebre = fiebre;
		this.tos = tos;
		this.secrecionNasal = secrecionNasal;
		this.dolorGarganta = dolorGarganta;
		this.congestionNasa = congestionNasa;
		this.dolorCabeza = dolorCabeza;
		this.faltaApetito = faltaApetito;
		this.dolorMuscular = dolorMuscular;
		this.dolorArticular = dolorArticular;
		this.dolorOido = dolorOido;
		this.respiracionRapida = respiracionRapida;
		this.dificultadRespirar = dificultadRespirar;
		this.faltaEscuela = faltaEscuela;
		this.quedoEnCama = quedoEnCama;
		/*Nuevos campos agregados 24/09/2019*/
		this.fiebreLeve = fiebreLeve;
		this.fiebreModerada = fiebreModerada;
		this.fiebreSevera = fiebreSevera;
		this.tosLeve = tosLeve;
		this.tosModerada = tosModerada;
		this.tosSevera = tosSevera;
		this.secrecionNasalLeve = secrecionNasalLeve;
		this.secrecionNasalModerada = secrecionNasalModerada;
		this.secrecionNasalSevera = secrecionNasalSevera;
		this.dolorGargantaLeve = dolorGargantaLeve;
		this.dolorGargantaModerada = dolorArticularModerada;
		this.dolorGargantaSevera = dolorGargantaSevera;
		this.dolorCabezaLeve = dolorCabezaLeve;
		this.dolorCabezaModerada = dolorCabezaModerada;
		this.dolorCabezaSevera = dolorCabezaSevera;
		this.dolorMuscularLeve = dolorMuscularLeve;
		this.dolorMuscularModerada = dolorMuscularModerada;
		this.dolorMuscularSevera = dolorMuscularSevera;
		this.dolorArticularLeve = dolorArticularLeve;
		this.dolorArticularModerada = dolorArticularModerada;
		this.dolorArticularSevera = dolorArticularSevera;
	}

	@Column(name = "sec_hoja_influenza", nullable = false)
	public int getSecHojaInfluenza() {
		return this.secHojaInfluenza;
	}

	public void setSecHojaInfluenza(int secHojaInfluenza) {
		this.secHojaInfluenza = secHojaInfluenza;
	}

	@Id
	@SequenceGenerator(name = "id_seg_influenza_sec", sequenceName = "seguimiento_influenza_sec_seg_influenza_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "id_seg_influenza_sec")
	@Column(name = "sec_seg_influenza", unique = true, nullable = false)
	public int getSecSegInfluenza() {
		return this.secSegInfluenza;
	}

	public void setSecSegInfluenza(int secSegInfluenza) {
		this.secSegInfluenza = secSegInfluenza;
	}

	@Column(name = "control_dia", nullable = false, length = 1)
	public int getControlDia() {
		return controlDia;
	}

	public void setControlDia(int controlDia) {
		this.controlDia = controlDia;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_seguimiento", nullable = false, length = 13)
	public Date getFechaSeguimiento() {
		return this.fechaSeguimiento;
	}


	public void setFechaSeguimiento(Date fechaSeguimiento) {
		this.fechaSeguimiento = fechaSeguimiento;
	}

	@Column(name = "usuario_medico", nullable = false)
	public short getUsuarioMedico() {
		return this.usuarioMedico;
	}

	public void setUsuarioMedico(short usuarioMedico) {
		this.usuarioMedico = usuarioMedico;
	}

	@Column(name = "consulta_inicial", nullable = false, length = 2)
	public String getConsultaInicial() {
		return this.consultaInicial;
	}

	public void setConsultaInicial(String consultaInicial) {
		this.consultaInicial = consultaInicial;
	}

	@Column(name = "fiebre", nullable = false, length = 2)
	public String getFiebre() {
		return this.fiebre;
	}

	public void setFiebre(String fiebre) {
		this.fiebre = fiebre;
	}

	@Column(name = "tos", nullable = false, length = 2)
	public String getTos() {
		return this.tos;
	}

	public void setTos(String tos) {
		this.tos = tos;
	}

	@Column(name = "secrecion_nasal", nullable = false, length = 2)
	public String getSecrecionNasal() {
		return this.secrecionNasal;
	}

	public void setSecrecionNasal(String secrecionNasal) {
		this.secrecionNasal = secrecionNasal;
	}

	@Column(name = "dolor_garganta", nullable = false, length = 2)
	public String getDolorGarganta() {
		return this.dolorGarganta;
	}

	public void setDolorGarganta(String dolorGarganta) {
		this.dolorGarganta = dolorGarganta;
	}

	@Column(name = "congestion_nasa", nullable = false, length = 2)
	public String getCongestionNasa() {
		return this.congestionNasa;
	}

	public void setCongestionNasa(String congestionNasa) {
		this.congestionNasa = congestionNasa;
	}

	@Column(name = "dolor_cabeza", nullable = false, length = 2)
	public String getDolorCabeza() {
		return this.dolorCabeza;
	}

	public void setDolorCabeza(String dolorCabeza) {
		this.dolorCabeza = dolorCabeza;
	}

	@Column(name = "falta_apetito", nullable = false, length = 2)
	public String getFaltaApetito() {
		return this.faltaApetito;
	}

	public void setFaltaApetito(String faltaApetito) {
		this.faltaApetito = faltaApetito;
	}

	@Column(name = "dolor_muscular", nullable = false, length = 2)
	public String getDolorMuscular() {
		return this.dolorMuscular;
	}

	public void setDolorMuscular(String dolorMuscular) {
		this.dolorMuscular = dolorMuscular;
	}

	@Column(name = "dolor_articular", nullable = false, length = 2)
	public String getDolorArticular() {
		return this.dolorArticular;
	}

	public void setDolorArticular(String dolorArticular) {
		this.dolorArticular = dolorArticular;
	}

	@Column(name = "dolor_oido", nullable = false, length = 2)
	public String getDolorOido() {
		return this.dolorOido;
	}

	public void setDolorOido(String dolorOido) {
		this.dolorOido = dolorOido;
	}

	@Column(name = "respiracion_rapida", nullable = false, length = 2)
	public String getRespiracionRapida() {
		return this.respiracionRapida;
	}

	public void setRespiracionRapida(String respiracionRapida) {
		this.respiracionRapida = respiracionRapida;
	}

	@Column(name = "dificultad_respirar", nullable = false, length = 2)
	public String getDificultadRespirar() {
		return this.dificultadRespirar;
	}

	public void setDificultadRespirar(String dificultadRespirar) {
		this.dificultadRespirar = dificultadRespirar;
	}

	@Column(name = "falta_escuela", nullable = false, length = 2)
	public String getFaltaEscuela() {
		return this.faltaEscuela;
	}

	public void setFaltaEscuela(String faltaEscuela) {
		this.faltaEscuela = faltaEscuela;
	}

	@Column(name = "quedo_en_cama", nullable = false, length = 2)
	public String getQuedoEnCama() {
		return this.quedoEnCama;
	}

	public void setQuedoEnCama(String quedoEnCama) {
		this.quedoEnCama = quedoEnCama;
	}

	/*Nuevos campos agregados 24/09/2019*/
	@Column(name = "fiebre_leve", length = 2)
	public String getFiebreLeve() {
		return fiebreLeve;
	}

	public void setFiebreLeve(String fiebreLeve) {
		this.fiebreLeve = fiebreLeve;
	}
	
	@Column(name = "fiebre_moderada", length = 2)
	public String getFiebreModerada() {
		return fiebreModerada;
	}

	public void setFiebreModerada(String fiebreModerada) {
		this.fiebreModerada = fiebreModerada;
	}

	@Column(name = "fiebre_severa", length = 2)
	public String getFiebreSevera() {
		return fiebreSevera;
	}

	public void setFiebreSevera(String fiebreSevera) {
		this.fiebreSevera = fiebreSevera;
	}

	@Column(name = "tos_leve", length = 2)
	public String getTosLeve() {
		return tosLeve;
	}

	public void setTosLeve(String tosLeve) {
		this.tosLeve = tosLeve;
	}

	@Column(name = "tos_moderada", length = 2)
	public String getTosModerada() {
		return tosModerada;
	}

	public void setTosModerada(String tosModerada) {
		this.tosModerada = tosModerada;
	}

	@Column(name = "tos_severa", length = 2)
	public String getTosSevera() {
		return tosSevera;
	}

	public void setTosSevera(String tosSevera) {
		this.tosSevera = tosSevera;
	}

	@Column(name = "secrecion_nasal_leve", length = 2)
	public String getSecrecionNasalLeve() {
		return secrecionNasalLeve;
	}

	public void setSecrecionNasalLeve(String secrecionNasalLeve) {
		this.secrecionNasalLeve = secrecionNasalLeve;
	}

	@Column(name = "secrecion_nasal_moderada", length = 2)
	public String getSecrecionNasalModerada() {
		return secrecionNasalModerada;
	}

	public void setSecrecionNasalModerada(String secrecionNasalModerada) {
		this.secrecionNasalModerada = secrecionNasalModerada;
	}

	@Column(name = "secrecion_nasal_severa", length = 2)
	public String getSecrecionNasalSevera() {
		return secrecionNasalSevera;
	}

	public void setSecrecionNasalSevera(String secrecionNasalSevera) {
		this.secrecionNasalSevera = secrecionNasalSevera;
	}

	@Column(name = "dolor_garganta_leve", length = 2)
	public String getDolorGargantaLeve() {
		return dolorGargantaLeve;
	}

	public void setDolorGargantaLeve(String dolorGargantaLeve) {
		this.dolorGargantaLeve = dolorGargantaLeve;
	}

	@Column(name = "dolor_garganta_moderada", length = 2)
	public String getDolorGargantaModerada() {
		return dolorGargantaModerada;
	}

	public void setDolorGargantaModerada(String dolorGargantaModerada) {
		this.dolorGargantaModerada = dolorGargantaModerada;
	}

	@Column(name = "dolor_garganta_severa", length = 2)
	public String getDolorGargantaSevera() {
		return dolorGargantaSevera;
	}

	public void setDolorGargantaSevera(String dolorGargantaSevera) {
		this.dolorGargantaSevera = dolorGargantaSevera;
	}

	@Column(name = "dolor_cabeza_leve", length = 2)
	public String getDolorCabezaLeve() {
		return dolorCabezaLeve;
	}

	public void setDolorCabezaLeve(String dolorCabezaLeve) {
		this.dolorCabezaLeve = dolorCabezaLeve;
	}

	@Column(name = "dolor_cabeza_moderada", length = 2)
	public String getDolorCabezaModerada() {
		return dolorCabezaModerada;
	}

	public void setDolorCabezaModerada(String dolorCabezaModerada) {
		this.dolorCabezaModerada = dolorCabezaModerada;
	}

	@Column(name = "dolor_cabeza_severa", length = 2)
	public String getDolorCabezaSevera() {
		return dolorCabezaSevera;
	}

	public void setDolorCabezaSevera(String dolorCabezaSevera) {
		this.dolorCabezaSevera = dolorCabezaSevera;
	}

	@Column(name = "dolor_muscular_leve", length = 2)
	public String getDolorMuscularLeve() {
		return dolorMuscularLeve;
	}

	public void setDolorMuscularLeve(String dolorMuscularLeve) {
		this.dolorMuscularLeve = dolorMuscularLeve;
	}
	
	@Column(name = "dolor_muscular_moderada", length = 2)
	public String getDolorMuscularModerada() {
		return dolorMuscularModerada;
	}

	public void setDolorMuscularModerada(String dolorMuscularModerada) {
		this.dolorMuscularModerada = dolorMuscularModerada;
	}
	
	@Column(name = "dolor_muscular_severa", length = 2)
	public String getDolorMuscularSevera() {
		return dolorMuscularSevera;
	}

	public void setDolorMuscularSevera(String dolorMuscularSevera) {
		this.dolorMuscularSevera = dolorMuscularSevera;
	}
	
	@Column(name = "dolor_articular_leve", length = 2)
	public String getDolorArticularLeve() {
		return dolorArticularLeve;
	}

	public void setDolorArticularLeve(String dolorArticularLeve) {
		this.dolorArticularLeve = dolorArticularLeve;
	}
	
	@Column(name = "dolor_articular_moderada", length = 2)
	public String getDolorArticularModerada() {
		return dolorArticularModerada;
	}

	public void setDolorArticularModerada(String dolorArticularModerada) {
		this.dolorArticularModerada = dolorArticularModerada;
	}
	
	@Column(name = "dolor_articular_severa", length = 2)
	public String getDolorArticularSevera() {
		return dolorArticularSevera;
	}

	public void setDolorArticularSevera(String dolorArticularSevera) {
		this.dolorArticularSevera = dolorArticularSevera;
	}

}
