package ni.com.sts.estudioCohorteCSSFV.modelo;

// Generated Oct 2, 2015 2:04:34 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SerologiaDengueMuestra generated by hbm2java
 */
@Entity
@Table(name = "serologia_dengue_muestra")
public class SerologiaDengueMuestra implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int secSerologiaDengue;
	private OrdenLaboratorio ordenLaboratorio;
	private String codigoMuestra;
	private Short usuarioBioanalista;
	private Date horaReporte;
	private Character estado;

	public SerologiaDengueMuestra() {
	}

	public SerologiaDengueMuestra(int secSerologiaDengue,
			OrdenLaboratorio ordenLaboratorio) {
		this.secSerologiaDengue = secSerologiaDengue;
		this.ordenLaboratorio = ordenLaboratorio;
	}

	public SerologiaDengueMuestra(int secSerologiaDengue,
			OrdenLaboratorio ordenLaboratorio, String codigoMuestra,
			Short usuarioBioanalista, Date horaReporte, Character estado) {
		this.secSerologiaDengue = secSerologiaDengue;
		this.ordenLaboratorio = ordenLaboratorio;
		this.codigoMuestra = codigoMuestra;
		this.usuarioBioanalista = usuarioBioanalista;
		this.horaReporte = horaReporte;
		this.estado = estado;
	}

	@Id
	@SequenceGenerator(name = "id_serologia_dengue_sec", sequenceName = "serologia_dengue_muestra_sec_serologia_dengue_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "id_serologia_dengue_sec")
	@Column(name = "sec_serologia_dengue", unique = true, nullable = false)
	public int getSecSerologiaDengue() {
		return this.secSerologiaDengue;
	}

	public void setSecSerologiaDengue(int secSerologiaDengue) {
		this.secSerologiaDengue = secSerologiaDengue;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sec_orden_laboratorio", nullable = false)
	public OrdenLaboratorio getOrdenLaboratorio() {
		return this.ordenLaboratorio;
	}

	public void setOrdenLaboratorio(OrdenLaboratorio ordenLaboratorio) {
		this.ordenLaboratorio = ordenLaboratorio;
	}

	@Column(name = "codigo_muestra", length = 50)
	public String getCodigoMuestra() {
		return this.codigoMuestra;
	}

	public void setCodigoMuestra(String codigoMuestra) {
		this.codigoMuestra = codigoMuestra;
	}

	@Column(name = "usuario_bioanalista")
	public Short getUsuarioBioanalista() {
		return this.usuarioBioanalista;
	}

	public void setUsuarioBioanalista(Short usuarioBioanalista) {
		this.usuarioBioanalista = usuarioBioanalista;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "hora_reporte", length = 29)
	public Date getHoraReporte() {
		return this.horaReporte;
	}

	public void setHoraReporte(Date horaReporte) {
		this.horaReporte = horaReporte;
	}

	@Column(name = "estado", length = 1)
	public Character getEstado() {
		return this.estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

}
