package ni.com.sts.estudioCohorteCSSFV.modelo;

// Generated 01-oct-2015 22:14:30 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TipoConsulta generated by hbm2java
 */
@Entity
@Table(name = "tipo_consulta", uniqueConstraints = @UniqueConstraint(columnNames = "sec_tipocon"))
public class TipoConsulta implements java.io.Serializable {

	private String codigo;
	private int secTipocon;
	private String descripcion;
	private char estado;

	public TipoConsulta() {
	}

	public TipoConsulta(String codigo, int secTipocon, String descripcion,
			char estado) {
		this.codigo = codigo;
		this.secTipocon = secTipocon;
		this.descripcion = descripcion;
		this.estado = estado;
	}

	@Column(name = "codigo", unique = true, nullable = false, length = 16)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Id	
	@SequenceGenerator(name = "id_tipo_consulta_sec_tipocon_seq", sequenceName = "tipo_consulta_sec_tipocon_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "id_tipo_consulta_sec_tipocon_seq")
	@Column(name = "sec_tipocon", unique = true, nullable = false)
	public int getSecTipocon() {
		return this.secTipocon;
	}

	public void setSecTipocon(int secTipocon) {
		this.secTipocon = secTipocon;
	}

	@Column(name = "descripcion", nullable = false, length = 32)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "estado", nullable = false, length = 1)
	public char getEstado() {
		return this.estado;
	}

	public void setEstado(char estado) {
		this.estado = estado;
	}

}
