package ni.com.sts.estudioCohorteCSSFV.modelo;
// Generated 04-30-2019 09:40:40 AM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VigilanciaIntegradaIragEti generated by hbm2java
 */
@Entity
@Table(name = "vigilancia_integrada_irag_eti")
public class VigilanciaIntegradaIragEti implements java.io.Serializable {

	private int secVigilanciaIntegrada;
	private int secHojaConsulta;
	private int codExpediente;
	private char irag;
	private char eti;
	private char iragInusitada;
	private String departamento;
	private String municipio;
	private String barrio;
	private String direccion;
	private String telefono;
	private Character urbano;
	private Character rural;
	private Character emergencia;
	private Character emergAmbulatorio;
	private Character sala;
	private Character uci;
	private String diagnostico;
	private Character presentTarjVacuna;
	private Character antiHib;
	private Character antiMeningococica;
	private Character antiNeumococica;
	private Character antiInfluenza;
	private Character pentavalente;
	private Character conjugada;
	private Character polisacarida;
	private Character heptavalente;
	private Character polisacarida23;
	private Character valente13;
	private Character estacional;
	private Character h1n1p;
	private Character otraVacuna;
	private Short noDosisAntiHib;
	private Short noDosisAntiMening;
	private Short noDosisAntiNeumo;
	private Short noDosisAntiInflu;
	private Date fechaUltDosisAntiHib;
	private Date fechaUltDosisAntiMening;
	private Date fechaUltDosisAntiNeumo;
	private Date fechaUltDosisAntiInflu;
	private Character cancer;
	private Character diabetes;
	private Character vih;
	private Character otraInmunodeficiencia;
	private Character enfNeurologicaCronica;
	private Character enfCardiaca;
	private Character asma;
	private Character epoc;
	private Character otraEnfPulmonar;
	private Character insufRenalCronica;
	private Character desnutricion;
	private Character obesidad;
	private Character embarazo;
	private Short embarazoSemanas;
	private Character txCorticosteroide;
	private Character otraCondicion;
	private Character usoAntibioticoUltimaSemana;
	private Short cuantosAntibioticosLeDio;
	private String cualesAntibioticosLeDio;
	private Short cuantosDiasLeDioElUltimoAntibiotico;
	private Character viaOral;
	private Character viaParenteral;
	private Character viaAmbas;
	private Character antecedentesUsoAntivirales;
	private String nombreAntiviral;
	private Date fecha1raDosis;
	private Date fechaUltimaDosis;
	private Short noDosisAdministrada;
	private Date fechaCreacion;
	private String otraCondPreexistente;
	private int numHojaConsulta;
	private Character estornudos;
	private Character otraManifestacionClinica;
	private String cualManifestacionClinica;

	public VigilanciaIntegradaIragEti() {
	}

	public VigilanciaIntegradaIragEti(int secVigilanciaIntegrada, int secHojaConsulta, int codExpediente, char irag,
			char eti, char iragInusitada) {
		this.secVigilanciaIntegrada = secVigilanciaIntegrada;
		this.secHojaConsulta = secHojaConsulta;
		this.codExpediente = codExpediente;
		this.irag = irag;
		this.eti = eti;
		this.iragInusitada = iragInusitada;
	}

	public VigilanciaIntegradaIragEti(int secVigilanciaIntegrada, int secHojaConsulta, int codExpediente, char irag,
			char eti, char iragInusitada, String departamento, String municipio, String barrio, String direccion,
			String telefono, Character urbano, Character rural, Character emergencia, Character emergAmbulatorio,
			Character sala, Character uci, String diagnostico, Character presentTarjVacuna, Character antiHib,
			Character antiMeningococica, Character antiNeumococica, Character antiInfluenza, Character pentavalente,
			Character conjugada, Character polisacarida, Character heptavalente, Character polisacarida23,
			Character valente13, Character estacional, Character h1n1p, Character otraVacuna, Short noDosisAntiHib,
			Short noDosisAntiMening, Short noDosisAntiNeumo, Short noDosisAntiInflu, Date fechaUltDosisAntiHib,
			Date fechaUltDosisAntiMening, Date fechaUltDosisAntiNeumo, Date fechaUltDosisAntiInflu, Character cancer,
			Character diabetes, Character vih, Character otraInmunodeficiencia, Character enfNeurologicaCronica,
			Character enfCardiaca, Character asma, Character epoc, Character otraEnfPulmonar,
			Character insufRenalCronica, Character desnutricion, Character obesidad, Character embarazo,
			Short embarazoSemanas, Character txCorticosteroide, Character otraCondicion,
			Character usoAntibioticoUltimaSemana, Short cuantosAntibioticosLeDio, String cualesAntibioticosLeDio,
			Short cuantosDiasLeDioElUltimoAntibiotico, Character viaOral, Character viaParenteral, Character viaAmbas,
			Character antecedentesUsoAntivirales, String nombreAntiviral, Date fecha1raDosis, Date fechaUltimaDosis,
			Short noDosisAdministrada, Date fechaCreacion, String otraCondPreexistente, int numHojaConsulta, Character estornudos,
			Character otraManifestacionClinica, String cualManifestacionClinica) {
		this.secVigilanciaIntegrada = secVigilanciaIntegrada;
		this.secHojaConsulta = secHojaConsulta;
		this.codExpediente = codExpediente;
		this.irag = irag;
		this.eti = eti;
		this.iragInusitada = iragInusitada;
		this.departamento = departamento;
		this.municipio = municipio;
		this.barrio = barrio;
		this.direccion = direccion;
		this.telefono = telefono;
		this.urbano = urbano;
		this.rural = rural;
		this.emergencia = emergencia;
		this.emergAmbulatorio = emergAmbulatorio;
		this.sala = sala;
		this.uci = uci;
		this.diagnostico = diagnostico;
		this.presentTarjVacuna = presentTarjVacuna;
		this.antiHib = antiHib;
		this.antiMeningococica = antiMeningococica;
		this.antiNeumococica = antiNeumococica;
		this.antiInfluenza = antiInfluenza;
		this.pentavalente = pentavalente;
		this.conjugada = conjugada;
		this.polisacarida = polisacarida;
		this.heptavalente = heptavalente;
		this.polisacarida23 = polisacarida23;
		this.valente13 = valente13;
		this.estacional = estacional;
		this.h1n1p = h1n1p;
		this.otraVacuna = otraVacuna;
		this.noDosisAntiHib = noDosisAntiHib;
		this.noDosisAntiMening = noDosisAntiMening;
		this.noDosisAntiNeumo = noDosisAntiNeumo;
		this.noDosisAntiInflu = noDosisAntiInflu;
		this.fechaUltDosisAntiHib = fechaUltDosisAntiHib;
		this.fechaUltDosisAntiMening = fechaUltDosisAntiMening;
		this.fechaUltDosisAntiNeumo = fechaUltDosisAntiNeumo;
		this.fechaUltDosisAntiInflu = fechaUltDosisAntiInflu;
		this.cancer = cancer;
		this.diabetes = diabetes;
		this.vih = vih;
		this.otraInmunodeficiencia = otraInmunodeficiencia;
		this.enfNeurologicaCronica = enfNeurologicaCronica;
		this.enfCardiaca = enfCardiaca;
		this.asma = asma;
		this.epoc = epoc;
		this.otraEnfPulmonar = otraEnfPulmonar;
		this.insufRenalCronica = insufRenalCronica;
		this.desnutricion = desnutricion;
		this.obesidad = obesidad;
		this.embarazo = embarazo;
		this.embarazoSemanas = embarazoSemanas;
		this.txCorticosteroide = txCorticosteroide;
		this.otraCondicion = otraCondicion;
		this.usoAntibioticoUltimaSemana = usoAntibioticoUltimaSemana;
		this.cuantosAntibioticosLeDio = cuantosAntibioticosLeDio;
		this.cualesAntibioticosLeDio = cualesAntibioticosLeDio;
		this.cuantosDiasLeDioElUltimoAntibiotico = cuantosDiasLeDioElUltimoAntibiotico;
		this.viaOral = viaOral;
		this.viaParenteral = viaParenteral;
		this.viaAmbas = viaAmbas;
		this.antecedentesUsoAntivirales = antecedentesUsoAntivirales;
		this.nombreAntiviral = nombreAntiviral;
		this.fecha1raDosis = fecha1raDosis;
		this.fechaUltimaDosis = fechaUltimaDosis;
		this.noDosisAdministrada = noDosisAdministrada;
		this.fechaCreacion = fechaCreacion;
		this.otraCondPreexistente = otraCondPreexistente;
		this.numHojaConsulta = numHojaConsulta;
		this.estornudos = estornudos;
		this.otraManifestacionClinica = otraManifestacionClinica;
		this.cualManifestacionClinica = cualManifestacionClinica;
	}

	@Id
	@SequenceGenerator(name = "id_vigilancia_integrada_sec", sequenceName = "vigilancia_integrada_irag_eti_sec_vigilancia_integrada_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "id_vigilancia_integrada_sec")
	@Column(name = "sec_vigilancia_integrada", unique = true, nullable = false)
	public int getSecVigilanciaIntegrada() {
		return this.secVigilanciaIntegrada;
	}

	public void setSecVigilanciaIntegrada(int secVigilanciaIntegrada) {
		this.secVigilanciaIntegrada = secVigilanciaIntegrada;
	}

	@Column(name = "sec_hoja_consulta", nullable = false)
	public int getSecHojaConsulta() {
		return this.secHojaConsulta;
	}

	public void setSecHojaConsulta(int secHojaConsulta) {
		this.secHojaConsulta = secHojaConsulta;
	}

	@Column(name = "cod_expediente", nullable = false)
	public int getCodExpediente() {
		return this.codExpediente;
	}

	public void setCodExpediente(int codExpediente) {
		this.codExpediente = codExpediente;
	}

	@Column(name = "irag", nullable = false, length = 1)
	public char getIrag() {
		return this.irag;
	}

	public void setIrag(char irag) {
		this.irag = irag;
	}

	@Column(name = "eti", nullable = false, length = 1)
	public char getEti() {
		return this.eti;
	}

	public void setEti(char eti) {
		this.eti = eti;
	}

	@Column(name = "irag_inusitada", nullable = false, length = 1)
	public char getIragInusitada() {
		return this.iragInusitada;
	}

	public void setIragInusitada(char iragInusitada) {
		this.iragInusitada = iragInusitada;
	}

	@Column(name = "departamento", length = 64)
	public String getDepartamento() {
		return this.departamento;
	}

	public void setDepartamento(String departamento) {
		this.departamento = departamento;
	}

	@Column(name = "municipio", length = 64)
	public String getMunicipio() {
		return this.municipio;
	}

	public void setMunicipio(String municipio) {
		this.municipio = municipio;
	}

	@Column(name = "barrio", length = 64)
	public String getBarrio() {
		return this.barrio;
	}

	public void setBarrio(String barrio) {
		this.barrio = barrio;
	}

	@Column(name = "direccion", length = 250)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "telefono", length = 10)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "urbano", length = 1)
	public Character getUrbano() {
		return this.urbano;
	}

	public void setUrbano(Character urbano) {
		this.urbano = urbano;
	}

	@Column(name = "rural", length = 1)
	public Character getRural() {
		return this.rural;
	}

	public void setRural(Character rural) {
		this.rural = rural;
	}

	@Column(name = "emergencia", length = 1)
	public Character getEmergencia() {
		return this.emergencia;
	}

	public void setEmergencia(Character emergencia) {
		this.emergencia = emergencia;
	}

	@Column(name = "emerg_ambulatorio", length = 1)
	public Character getEmergAmbulatorio() {
		return this.emergAmbulatorio;
	}

	public void setEmergAmbulatorio(Character emergAmbulatorio) {
		this.emergAmbulatorio = emergAmbulatorio;
	}

	@Column(name = "sala", length = 1)
	public Character getSala() {
		return this.sala;
	}

	public void setSala(Character sala) {
		this.sala = sala;
	}

	@Column(name = "uci", length = 1)
	public Character getUci() {
		return this.uci;
	}

	public void setUci(Character uci) {
		this.uci = uci;
	}

	@Column(name = "diagnostico", length = 64)
	public String getDiagnostico() {
		return this.diagnostico;
	}

	public void setDiagnostico(String diagnostico) {
		this.diagnostico = diagnostico;
	}

	@Column(name = "present_tarj_vacuna", length = 1)
	public Character getPresentTarjVacuna() {
		return this.presentTarjVacuna;
	}

	public void setPresentTarjVacuna(Character presentTarjVacuna) {
		this.presentTarjVacuna = presentTarjVacuna;
	}

	@Column(name = "anti_hib", length = 1)
	public Character getAntiHib() {
		return this.antiHib;
	}

	public void setAntiHib(Character antiHib) {
		this.antiHib = antiHib;
	}

	@Column(name = "anti_meningococica", length = 1)
	public Character getAntiMeningococica() {
		return this.antiMeningococica;
	}

	public void setAntiMeningococica(Character antiMeningococica) {
		this.antiMeningococica = antiMeningococica;
	}

	@Column(name = "anti_neumococica", length = 1)
	public Character getAntiNeumococica() {
		return this.antiNeumococica;
	}

	public void setAntiNeumococica(Character antiNeumococica) {
		this.antiNeumococica = antiNeumococica;
	}

	@Column(name = "anti_influenza", length = 1)
	public Character getAntiInfluenza() {
		return this.antiInfluenza;
	}

	public void setAntiInfluenza(Character antiInfluenza) {
		this.antiInfluenza = antiInfluenza;
	}

	@Column(name = "pentavalente", length = 1)
	public Character getPentavalente() {
		return this.pentavalente;
	}

	public void setPentavalente(Character pentavalente) {
		this.pentavalente = pentavalente;
	}

	@Column(name = "conjugada", length = 1)
	public Character getConjugada() {
		return this.conjugada;
	}

	public void setConjugada(Character conjugada) {
		this.conjugada = conjugada;
	}

	@Column(name = "polisacarida", length = 1)
	public Character getPolisacarida() {
		return this.polisacarida;
	}

	public void setPolisacarida(Character polisacarida) {
		this.polisacarida = polisacarida;
	}

	@Column(name = "heptavalente", length = 1)
	public Character getHeptavalente() {
		return this.heptavalente;
	}

	public void setHeptavalente(Character heptavalente) {
		this.heptavalente = heptavalente;
	}

	@Column(name = "polisacarida_23", length = 1)
	public Character getPolisacarida23() {
		return this.polisacarida23;
	}

	public void setPolisacarida23(Character polisacarida23) {
		this.polisacarida23 = polisacarida23;
	}

	@Column(name = "valente_13", length = 1)
	public Character getValente13() {
		return this.valente13;
	}

	public void setValente13(Character valente13) {
		this.valente13 = valente13;
	}

	@Column(name = "estacional", length = 1)
	public Character getEstacional() {
		return this.estacional;
	}

	public void setEstacional(Character estacional) {
		this.estacional = estacional;
	}

	@Column(name = "h1n1p", length = 1)
	public Character getH1n1p() {
		return this.h1n1p;
	}

	public void setH1n1p(Character h1n1p) {
		this.h1n1p = h1n1p;
	}

	@Column(name = "otra_vacuna", length = 1)
	public Character getOtraVacuna() {
		return this.otraVacuna;
	}

	public void setOtraVacuna(Character otraVacuna) {
		this.otraVacuna = otraVacuna;
	}

	@Column(name = "no_dosis_anti_hib")
	public Short getNoDosisAntiHib() {
		return this.noDosisAntiHib;
	}

	public void setNoDosisAntiHib(Short noDosisAntiHib) {
		this.noDosisAntiHib = noDosisAntiHib;
	}

	@Column(name = "no_dosis_anti_mening")
	public Short getNoDosisAntiMening() {
		return this.noDosisAntiMening;
	}

	public void setNoDosisAntiMening(Short noDosisAntiMening) {
		this.noDosisAntiMening = noDosisAntiMening;
	}

	@Column(name = "no_dosis_anti_neumo")
	public Short getNoDosisAntiNeumo() {
		return this.noDosisAntiNeumo;
	}

	public void setNoDosisAntiNeumo(Short noDosisAntiNeumo) {
		this.noDosisAntiNeumo = noDosisAntiNeumo;
	}

	@Column(name = "no_dosis_anti_influ")
	public Short getNoDosisAntiInflu() {
		return this.noDosisAntiInflu;
	}

	public void setNoDosisAntiInflu(Short noDosisAntiInflu) {
		this.noDosisAntiInflu = noDosisAntiInflu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_ult_dosis_anti_hib", length = 13)
	public Date getFechaUltDosisAntiHib() {
		return this.fechaUltDosisAntiHib;
	}

	public void setFechaUltDosisAntiHib(Date fechaUltDosisAntiHib) {
		this.fechaUltDosisAntiHib = fechaUltDosisAntiHib;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_ult_dosis_anti_mening", length = 13)
	public Date getFechaUltDosisAntiMening() {
		return this.fechaUltDosisAntiMening;
	}

	public void setFechaUltDosisAntiMening(Date fechaUltDosisAntiMening) {
		this.fechaUltDosisAntiMening = fechaUltDosisAntiMening;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_ult_dosis_anti_neumo", length = 13)
	public Date getFechaUltDosisAntiNeumo() {
		return this.fechaUltDosisAntiNeumo;
	}

	public void setFechaUltDosisAntiNeumo(Date fechaUltDosisAntiNeumo) {
		this.fechaUltDosisAntiNeumo = fechaUltDosisAntiNeumo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_ult_dosis_anti_influ", length = 13)
	public Date getFechaUltDosisAntiInflu() {
		return this.fechaUltDosisAntiInflu;
	}

	public void setFechaUltDosisAntiInflu(Date fechaUltDosisAntiInflu) {
		this.fechaUltDosisAntiInflu = fechaUltDosisAntiInflu;
	}

	@Column(name = "cancer", length = 1)
	public Character getCancer() {
		return this.cancer;
	}

	public void setCancer(Character cancer) {
		this.cancer = cancer;
	}

	@Column(name = "diabetes", length = 1)
	public Character getDiabetes() {
		return this.diabetes;
	}

	public void setDiabetes(Character diabetes) {
		this.diabetes = diabetes;
	}

	@Column(name = "vih", length = 1)
	public Character getVih() {
		return this.vih;
	}

	public void setVih(Character vih) {
		this.vih = vih;
	}

	@Column(name = "otra_inmunodeficiencia", length = 1)
	public Character getOtraInmunodeficiencia() {
		return this.otraInmunodeficiencia;
	}

	public void setOtraInmunodeficiencia(Character otraInmunodeficiencia) {
		this.otraInmunodeficiencia = otraInmunodeficiencia;
	}

	@Column(name = "enf_neurologica_cronica", length = 1)
	public Character getEnfNeurologicaCronica() {
		return this.enfNeurologicaCronica;
	}

	public void setEnfNeurologicaCronica(Character enfNeurologicaCronica) {
		this.enfNeurologicaCronica = enfNeurologicaCronica;
	}

	@Column(name = "enf_cardiaca", length = 1)
	public Character getEnfCardiaca() {
		return this.enfCardiaca;
	}

	public void setEnfCardiaca(Character enfCardiaca) {
		this.enfCardiaca = enfCardiaca;
	}

	@Column(name = "asma", length = 1)
	public Character getAsma() {
		return this.asma;
	}

	public void setAsma(Character asma) {
		this.asma = asma;
	}

	@Column(name = "epoc", length = 1)
	public Character getEpoc() {
		return this.epoc;
	}

	public void setEpoc(Character epoc) {
		this.epoc = epoc;
	}

	@Column(name = "otra_enf_pulmonar", length = 1)
	public Character getOtraEnfPulmonar() {
		return this.otraEnfPulmonar;
	}

	public void setOtraEnfPulmonar(Character otraEnfPulmonar) {
		this.otraEnfPulmonar = otraEnfPulmonar;
	}

	@Column(name = "insuf_renal_cronica", length = 1)
	public Character getInsufRenalCronica() {
		return this.insufRenalCronica;
	}

	public void setInsufRenalCronica(Character insufRenalCronica) {
		this.insufRenalCronica = insufRenalCronica;
	}

	@Column(name = "desnutricion", length = 1)
	public Character getDesnutricion() {
		return this.desnutricion;
	}

	public void setDesnutricion(Character desnutricion) {
		this.desnutricion = desnutricion;
	}

	@Column(name = "obesidad", length = 1)
	public Character getObesidad() {
		return this.obesidad;
	}

	public void setObesidad(Character obesidad) {
		this.obesidad = obesidad;
	}

	@Column(name = "embarazo", length = 1)
	public Character getEmbarazo() {
		return this.embarazo;
	}

	public void setEmbarazo(Character embarazo) {
		this.embarazo = embarazo;
	}

	@Column(name = "embarazo_semanas")
	public Short getEmbarazoSemanas() {
		return this.embarazoSemanas;
	}

	public void setEmbarazoSemanas(Short embarazoSemanas) {
		this.embarazoSemanas = embarazoSemanas;
	}

	@Column(name = "tx_corticosteroide", length = 1)
	public Character getTxCorticosteroide() {
		return this.txCorticosteroide;
	}

	public void setTxCorticosteroide(Character txCorticosteroide) {
		this.txCorticosteroide = txCorticosteroide;
	}

	@Column(name = "otra_condicion", length = 1)
	public Character getOtraCondicion() {
		return this.otraCondicion;
	}

	public void setOtraCondicion(Character otraCondicion) {
		this.otraCondicion = otraCondicion;
	}

	@Column(name = "uso_antibiotico_ultima_semana", length = 1)
	public Character getUsoAntibioticoUltimaSemana() {
		return this.usoAntibioticoUltimaSemana;
	}

	public void setUsoAntibioticoUltimaSemana(Character usoAntibioticoUltimaSemana) {
		this.usoAntibioticoUltimaSemana = usoAntibioticoUltimaSemana;
	}

	@Column(name = "cuantos_antibioticos_le_dio")
	public Short getCuantosAntibioticosLeDio() {
		return this.cuantosAntibioticosLeDio;
	}

	public void setCuantosAntibioticosLeDio(Short cuantosAntibioticosLeDio) {
		this.cuantosAntibioticosLeDio = cuantosAntibioticosLeDio;
	}

	@Column(name = "cuales_antibioticos_le_dio", length = 64)
	public String getCualesAntibioticosLeDio() {
		return this.cualesAntibioticosLeDio;
	}

	public void setCualesAntibioticosLeDio(String cualesAntibioticosLeDio) {
		this.cualesAntibioticosLeDio = cualesAntibioticosLeDio;
	}

	@Column(name = "cuantos_dias_le_dio_el_ultimo_antibiotico")
	public Short getCuantosDiasLeDioElUltimoAntibiotico() {
		return this.cuantosDiasLeDioElUltimoAntibiotico;
	}

	public void setCuantosDiasLeDioElUltimoAntibiotico(Short cuantosDiasLeDioElUltimoAntibiotico) {
		this.cuantosDiasLeDioElUltimoAntibiotico = cuantosDiasLeDioElUltimoAntibiotico;
	}

	@Column(name = "via_oral", length = 1)
	public Character getViaOral() {
		return this.viaOral;
	}

	public void setViaOral(Character viaOral) {
		this.viaOral = viaOral;
	}

	@Column(name = "via_parenteral", length = 1)
	public Character getViaParenteral() {
		return this.viaParenteral;
	}

	public void setViaParenteral(Character viaParenteral) {
		this.viaParenteral = viaParenteral;
	}

	@Column(name = "via_ambas", length = 1)
	public Character getViaAmbas() {
		return this.viaAmbas;
	}

	public void setViaAmbas(Character viaAmbas) {
		this.viaAmbas = viaAmbas;
	}

	@Column(name = "antecedentes_uso_antivirales", length = 1)
	public Character getAntecedentesUsoAntivirales() {
		return this.antecedentesUsoAntivirales;
	}

	public void setAntecedentesUsoAntivirales(Character antecedentesUsoAntivirales) {
		this.antecedentesUsoAntivirales = antecedentesUsoAntivirales;
	}

	@Column(name = "nombre_antiviral", length = 64)
	public String getNombreAntiviral() {
		return this.nombreAntiviral;
	}

	public void setNombreAntiviral(String nombreAntiviral) {
		this.nombreAntiviral = nombreAntiviral;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_1ra_dosis", length = 13)
	public Date getFecha1raDosis() {
		return this.fecha1raDosis;
	}

	public void setFecha1raDosis(Date fecha1raDosis) {
		this.fecha1raDosis = fecha1raDosis;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_ultima_dosis", length = 13)
	public Date getFechaUltimaDosis() {
		return this.fechaUltimaDosis;
	}

	public void setFechaUltimaDosis(Date fechaUltimaDosis) {
		this.fechaUltimaDosis = fechaUltimaDosis;
	}

	@Column(name = "no_dosis_administrada")
	public Short getNoDosisAdministrada() {
		return this.noDosisAdministrada;
	}

	public void setNoDosisAdministrada(Short noDosisAdministrada) {
		this.noDosisAdministrada = noDosisAdministrada;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion", length = 29)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "otra_cond_preexistente", length = 64)
	public String getOtraCondPreexistente() {
		return this.otraCondPreexistente;
	}

	public void setOtraCondPreexistente(String otraCondPreexistente) {
		this.otraCondPreexistente = otraCondPreexistente;
	}

	@Column(name = "num_hoja_consulta")
	public int getNumHojaConsulta() {
		return this.numHojaConsulta;
	}

	public void setNumHojaConsulta(int numHojaConsulta) {
		this.numHojaConsulta = numHojaConsulta;
	}
	
	@Column(name = "estornudos", length = 1)
	public Character getEstornudos() {
		return this.estornudos;
	}

	public void setEstornudos(Character estornudos) {
		this.estornudos = estornudos;
	}
	@Column(name = "otra_manifestacion_clinica", length = 1)
	public Character getOtraManifestacionClinica() {
		return this.otraManifestacionClinica;
	}
	public void setOtraManifestacionClinica(Character otraManifestacionClinica) {
		this.otraManifestacionClinica = otraManifestacionClinica;
	}
	@Column(name = "cual_manifestacion_clinica", length = 4)
	public String getCualManifestacionClinica() {
		return this.cualManifestacionClinica;
	}
	public void setCualManifestacionClinica(String cualManifestacionClinica) {
		this.cualManifestacionClinica = cualManifestacionClinica;
	}
}
